### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by kumamoto** [serenader2014/flutter_carousel_slider#1]
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
'package:flutter/src/widgets/page_view.dart': Failed assertion: line 96 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
#2      PageController.page (package:flutter/src/widgets/page_view.dart)
#3      PageController.nextPage (package:flutter/src/widgets/page_view.dart:142:26)
#4      _CarouselSliderState.initState.<anonymous closure> (package:carousel_slider/carousel_slider.dart:87:31)
#5      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#6      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

**Comment by serenader2014** [comment]
What environment are you using? Flutter version? Device version?

**Comment by kumamoto** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E202, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.7)
[!] VS Code (version 1.24.0)
[✓] Connected devices (2 available)

**Comment by serenader2014** [comment]
Hello, sorry for the late response. I've fix this bug in v0.0.5, please try again.

Also noted, currently the package in pub.dartlang.org is still in v0.0.4, I can not publish my package to the pub, I have open an issue on the pub's GitHub repo. In the meantime you can only install this package using git url. Sorry for the inconvenience.

**Comment by serenader2014** [comment]
The package is published to the pub.dartlang.org, and I'm closing this issue since there is no response after my last comment.
