### ISSUE TITLE
Can I remove spacing and the "growing" animation between slides?

### ISSUE THREAD

**Issue by toureh** [serenader2014/flutter_carousel_slider#10]
Hi! Is there any way to remove spacing between slides as they scroll and to remove the "growing" animation on the incoming slide?
cheers!

**Comment by serenader2014** [comment]
After the v1.0.0 release, you can achieve this by setting the `distortion`  to `false`, for example:

```dart
            Padding(
              padding: EdgeInsets.symmetric(vertical: 15.0),
              child: CarouselSlider(
                items: map<Widget>(imgList, (index, i) {
                  return Container(
                    decoration: BoxDecoration(
                      image: DecorationImage(
                        image: NetworkImage(i),
                        fit: BoxFit.cover
                      )
                    ),
                  );
                }),
                autoPlay: false,
                viewportFraction: 1.0,
                aspectRatio: 2.0,
                distortion: false
              )
            ),
```

Just to make sure the `distortion` is set to `false`, and `viewportFraction` is set to `1.0`, and you're done.

**Comment by crnaosa** [comment]
Hello there, thank you for the plugin. I like it very much, but I have a problem. I am using version 1.3.0. but there is no distortion field in this version. How to reduce the space between slides without it? Thanks!

**Comment by joelbrostrom** [comment]
Hi!

Did you try setting `viewportFraction: 1.0`?
This will make the carousel items cover all of the carousels available space.
If you want specific padding after that you can always wrap the items in a padding widget (pro tip; select the widget you want to pad and press ⌘+Enter and Padding should be the first option).

Here I modified the `Pages covers entire carousel` from the example code.
Try it out and see if it helps.

```
//Pages covers entire carousel
    final CarouselSlider coverScreenExample = CarouselSlider(
      viewportFraction: 1.0,
      aspectRatio: 2.0,
      autoPlay: false,
      enlargeCenterPage: false,
      items: map<Widget>(
        imgList,
        (index, i) {
          return Padding(
            padding: const EdgeInsets.all(8.0),
            child: Container(
              decoration: BoxDecoration(
                image: DecorationImage(image: NetworkImage(i), fit: BoxFit.cover),
              ),
            ),
          );
        },
      ),
    );
```
