### ISSUE TITLE
dot indicator using carousel.builder

### ISSUE THREAD

**Issue by brizaldi** [serenader2014/flutter_carousel_slider#104]
please add support for dot indicator using carousel.builder

**Comment by selvas1998** [comment]
> please add support for dot indicator using carousel.builder

You can do manually with **Stack** widget and **Positioned** widget

**Comment by brizaldi** [comment]
what if i want to put it inside listview.builder as an item?

**Comment by serenader2014** [comment]
Hi, sorry for the late response.

Currently you can't build the indicator in the item builder. As @selvas1998 mentioned, you can create a Stack widget and a Positioned widget to achieve this.

For a more detailed example please take a look at example folder.
