### ISSUE TITLE
showing multiple image in a single viewport

### ISSUE THREAD

**Issue by jpainam** [serenader2014/flutter_carousel_slider#107]
Hi, is it possible to extend the view to fill the viewport. I would like to show three item per viewport and apply infinite scrolling
![image](https://user-images.githubusercontent.com/1701705/75269505-fa0db480-5833-11ea-8798-3ca9dee489a7.png)

```dart
return CarouselSlider(
        items: _items,
        autoPlay: true,
        initialPage: 0,
        viewportFraction: .3,
        aspectRatio: 1.0,
        enlargeCenterPage: true,
        scrollPhysics: const AlwaysScrollableScrollPhysics(),
        scrollDirection: Axis.horizontal,
        reverse: false,
        enableInfiniteScroll: true,
        autoPlayInterval: Duration(seconds: 3),
        autoPlayAnimationDuration: Duration(milliseconds: 800),
        autoPlayCurve: Curves.easeInOutBack,
        pauseAutoPlayOnTouch: Duration(seconds: 10),
      );
```

The three image are squeeze and doesn't fill the viewport. i I apply `viewportFraction= 3. `It shows a single items that fills 1/3 of the width.
Thank you

**Comment by serenader2014** [comment]
I'm closing this issue since it's duplicated of #108
