### ISSUE TITLE
Animate inserting and removing items

### ISSUE THREAD

**Issue by ernesto-handy** [serenader2014/flutter_carousel_slider#109]
Is it possible to animate inserting and removing items like in an AnimatedList?

**Comment by serenader2014** [comment]
Sorry for the late response.

Currently animating inserting or removing is not supported. :(

**Comment by vorant94** [comment]
@serenader2014 is it still not supported?

**Comment by uynguyen** [comment]
Anyone has any idea to make it works? ...
