### ISSUE TITLE
Child widget pops into existence 

### ISSUE THREAD

**Issue by jacksonw765** [serenader2014/flutter_carousel_slider#111]
New to using this plugin (which I really love, great job) but there seems to be an issue when using an offset value like the one I have specified. The container just pops into existence on the screen.  

    Align(
            alignment: Alignment.bottomCenter,
            child: CarouselSlider(
              height: 500.0,
              enableInfiniteScroll: false,
              enlargeCenterPage: true,
              viewportFraction: .7,
              onPageChanged: (int index) => setState(() => _index = index),
              items: [1, 2, 3, 4, 5].map((i) {
                return Builder(
                  builder: (BuildContext context) {
                    final double blur = i == _index+1 ? 25 : 0.0;
                    final double offset = i == _index+1 ? 8 : 0;
                    final double top = i == _index+1 ? 70 : 160;
                    return Transform.translate(
                      offset: Offset(-35,0),
                      child: AnimatedContainer(
                        margin: EdgeInsets.only(top: top, bottom: 70, right: 30),
                        duration: Duration(milliseconds: 500),
                        curve: Curves.easeOutQuint,
                        width: 250,
                        decoration: BoxDecoration(
                          boxShadow: [BoxShadow(color: Colors.black38, blurRadius: blur, offset: Offset(offset, offset*2))],
                          borderRadius: BorderRadius.all(Radius.circular(20.0)),
                          color: Colors.amber,
                        ),
                        child: Center(child: Text('hello' + (_index+1).toString())),
                      ),
                    );
                  },
                );
              }).toList(),
            ),
          ),

**Comment by serenader2014** [comment]
Sorry for the late response.

I have tested the code you gave, but I don't know what's the problem. Here is my screenshot:

![image](https://user-images.githubusercontent.com/6716522/79121858-e4932080-7dc8-11ea-8211-0533f7d0e11c.png)

**Comment by jacksonw765** [comment]
Sorry I found a workaround but the issue by using padding and margins. The issue was that I didn't want the card layout to be centered I wanted it to be offset slightly. The issue was that the card on the right just pops into place if you slide it right to left.

**Comment by serenader2014** [comment]
Great to hear that you've found the workaround.

Also I'm planning to add an option to let user to disable the `Center` widget, so the carousel item doesn't need to be centered. Will update this issue when I release this feature.

**Comment by serenader2014** [comment]
Hi @jacksonw765 , just want to let you know that I have released a new version, and provide a way to disable the `Center` widget, please upgrade to v2.2.0 and give it a try.

I'm closing this issue, but if you have any further issues, feel free to reopen it.

**Comment by setu-dev** [comment]
@serenader2014 can you please drop an example of how to left align the first item of the carousel if viewportFraction is 0.7.
