### ISSUE TITLE
Possible to load x images in advance to cache?

### ISSUE THREAD

**Issue by guit4eva** [serenader2014/flutter_carousel_slider#114]
When building item widgets on demand, is it possible to load x number of widgets in advance? ie, with an image slider, have the next two images loading into cache while still offscreen.

**Comment by nicolasvahidzein** [comment]
this is a great idea, i was coming here to second this. We need to preload because as it is, the next image is not loaded and we have a blank screen when the slider shows, it is not good

**Comment by guit4eva** [comment]
> this is a great idea, i was coming here to second this. We need to preload because as it is, the next image is not loaded and we have a blank screen when the slider shows, it is not good

Flutter has a precacheImage() function which could help 👍🏼

**Comment by nicolasvahidzein** [comment]
guys just use this in your stack. It's hidden and you will be fine. Contact me and i'll guide you. Works like a charm.

```
				//background preloader
				Wrap(
					children: widget.orderSlider.list.map((item) => Container(
						width: 0,
						height: 0,
						color: Colors.white,
						child: Image(
							image: CachedNetworkImageProvider(item.image)
						),
					)).toList().cast<Widget>(),
				)
```

**Comment by nicolasvahidzein** [comment]
This is the more complete example of how i use the carousel slider:

```
//flutter packages
import 'package:flutter/material.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:cached_network_image/cached_network_image.dart';

//project packages
import 'package:zandumobile/utils/app_config.dart' as config;
import 'package:zandumobile/models/slider.dart';
import 'package:zandumobile/models/slider.dart' as prefix0;

class HomeSlider extends StatefulWidget {
	final SliderList sliderList;
	
	HomeSlider({
		@required this.sliderList,
	});
	
	@override
	_HomeSliderState createState() => _HomeSliderState();
	
}

class _HomeSliderState extends State<HomeSlider> {
	final String _fileName = 'home_slider.dart';
	int _current = 0;
	
	@override
	initState() {
		
		super.initState();
	}
	
	//determine if we show the button
	bool _buttonVisible(prefix0.Slider slide) {
		print('_buttonVisible function inside $_fileName');
		
		if (slide.button == null || slide.button == '') {
			return false;
		} else {
			return true;
		}
		
	}
	
	@override
	Widget build(BuildContext context) {
		return Stack(
			alignment: AlignmentDirectional.bottomEnd,
			// fit: StackFit.expand,
			children: <Widget>[
				
				CarouselSlider(
					autoPlay: true,
					autoPlayInterval: Duration(seconds: 5),
					height: 240,
					viewportFraction: 1.0,
					onPageChanged: (index) {
						setState(() {
							_current = index;
						});
					},
					items: widget.sliderList.list.map((prefix0.Slider slide) {
						return Builder(
							builder: (BuildContext context) {
								return Container(
									// margin: const EdgeInsets.symmetric(vertical: 20, horizontal: 20), //removed the padding
									height: 200,
									decoration: BoxDecoration(
										image: DecorationImage(
											image: CachedNetworkImageProvider(slide.image),
											// fit: BoxFit.cover,
											fit: BoxFit.contain,
										),
										color: Colors.white,
									),
									child: Container(
										alignment: AlignmentDirectional.bottomEnd,
										width: double.infinity,
										padding: const EdgeInsets.symmetric(horizontal: 20),
										child: Container(
											width: config.App(context).appWidth(40),
											child: Column(
												crossAxisAlignment: CrossAxisAlignment.stretch,
												mainAxisSize: MainAxisSize.max,
												mainAxisAlignment: MainAxisAlignment.spaceEvenly,
												children: <Widget>[
													
													//text
													Text(
														slide.description,
														style: Theme.of(context).textTheme.title.merge(
																	TextStyle(
																		height: 0.8,
																		// color: Colors.white,
																		color: Theme.of(context).primaryColor,
																	),
																),
														textAlign: TextAlign.right,
														overflow: TextOverflow.fade,
														maxLines: 3,
													),
													
													//button
													Visibility(
														visible: _buttonVisible(slide),
														child: FlatButton(
															onPressed: () {
																//  Navigator.of(context).pushNamed('/Checkout');
															},
															padding: EdgeInsets.symmetric(vertical: 5),
															color: Theme.of(context).accentColor,
															shape: StadiumBorder(),
															child: Text(
																slide.button,
																textAlign: TextAlign.start,
																style: TextStyle(
																	color: Colors.white, //NEXT_UPDATE replace this with a theme color as it should be
																),
															),
														),
													),
													
												],
											),
										),
									),
								);
							},
						);
					}).toList(),
				),
				
				Positioned(
					bottom: 0,
					right: 10,
					// width: config.App(context).appWidth(100),
					child: Row(
						mainAxisAlignment: MainAxisAlignment.end,
						children: widget.sliderList.list.map((prefix0.Slider slide) {
							return Container(
								width: 20.0,
								height: 3.0,
								margin: EdgeInsets.symmetric(vertical: 10.0, horizontal: 2.0),
								decoration: BoxDecoration(
									borderRadius: BorderRadius.all(
										Radius.circular(8),
									),
									color: _current == widget.sliderList.list.indexOf(slide)
											? Theme.of(context).primaryColor
											: Theme.of(context).primaryColor.withOpacity(0.3)
								),
							);
						}).toList(),
					),
				),
				
				//background preloader
				Wrap(
					children: widget.sliderList.list.map((item) => Container(
						width: 0,
						height: 0,
						color: Colors.white,
						child: Image(
							image: CachedNetworkImageProvider(item.image)
						),
					)).toList().cast<Widget>(),
				)
				
			],
		);
	}
}

```

**Comment by serenader2014** [comment]
Hey guys, sorry for the late response.

This is a great idea, and I think it's a very common use case. But currently I don't have any solution or suggestion on this, but I'll take my time to look into it.

By the mean time, you can take a look at @nicolasvahidzein 's workaround, to see if it is working or not.

**Comment by nicolasvahidzein** [comment]
Its working perfectly. Try it as well.

**Comment by serenader2014** [comment]
I have added the prefetch demo in the example project, please give it a try.

**Comment by nicolasvahidzein** [comment]
Wonderful thanks, looks better than my solution, you should add it to the read me in a prominent place, people will absolutely want to use this feature.

**Comment by nicolasvahidzein** [comment]
Tried it and it's not working well at all, my technique is better and loads the images nicely, with prefetch often times it does not load it in time. I will be reverting to my approach. Thanks.

**Comment by nicolasvahidzein** [comment]
Hello again, this is proving to be quite a problem, loading many images makes the app unusable for slow connections and loads unnecessary images and also makes the carousel slide without knowing if the image is loaded. We end up scrolling over blank placeholders multiple times.

**Comment by jtkeyva** [comment]
@nicolasvahidzein did you ever find a stable solution? how about with video?
thanks

**Comment by nicolasvahidzein** [comment]
the trick shown above works great, add an invisible row with all your images, or use the cache method described in the new version. Cheers.

**Comment by nicolasvahidzein** [comment]
@jtkeyva i have not tried video yet, my apologies. Video however should not be cached as it is usually something you stream.

**Comment by jtkeyva** [comment]
@nicolasvahidzein cool, thanks! i used a similar solution with css to load images in a hidden layer for a web project. to be clear, your previous comment about "proving to be quite a problem" was not for your solution...correct?

yeah, i'd like to prefetch the videos so there is no delay between slides. i'm on the fence with caching, but there's really no drawback to cache is there? as long as you clear out the cache so it doesn't bloat out of control.

have you tested the limit on a big list of images? any luck with lazy loading? i suppose you could lazy load another hidden element with your trick too?

thank you

**Comment by nicolasvahidzein** [comment]
@jtkeyva how would you lazy load these images i'm curious. I already know i'll only be doing 3 to 7 images so it's not a big deal. I need to look at my code again though because i might have changed the approach. Ideally you would only prefetch the next image.

**Comment by jtkeyva** [comment]
@nicolasvahidzein not sure, that's what i'm trying to find a solution for. ideally it would be an endless list of content that you can flip through which will prefetch as you cycle through. seems straight forward but haven't found a pre-made solution yet. any ideas greatly appreciated. thanks!

**Comment by Fnalsk** [comment]
I tried the precaching solution and that causes the app to crash if there are too many images to preload, as it requires way too much memory. 

I'd also like a solution involving x number of images to the left and right of the current image to be loaded at all times.

**Comment by mehul425** [comment]
I think this is possible you replace ViewPager with this package [preload_page_view(https://pub.dev/packages/preload_page_view)

**Comment by jfk4080** [comment]
Already someone found a proven solution?

**Comment by muziri** [comment]
Can we set allowImplicitScrolling = true for PageView?
