### ISSUE TITLE
Error last image when enableInfiniteScroll: false

### ISSUE THREAD

**Issue by nguyenvanquan7826** [serenader2014/flutter_carousel_slider#117]
Hi, when I set enableInfiniteScroll: false, the last image still animation next but it auto come back because it is last. And it loop Infinite.

**Comment by serenader2014** [comment]
Sorry for the late response.

Yes, currently this works as intended. The `enableInfiniteScroll` option only control whether the carousel should go to the first item or not, when it is at the last one.

However, the auto slide part is controlled by the `autoPlay` option, if you enable the `autoPlay` option, it will still go to the first item, even if it is at the last one.

But I think maybe we can add another option to solve this situation.

**Comment by serenader2014** [comment]
Fixed in v2.1.0

**Comment by Nurgunkalol** [comment]
im using v2.3.1 but still have this problem
