### ISSUE TITLE
数据列表的长度为0时报错

### ISSUE THREAD

**Issue by woshiyizhijiao** [serenader2014/flutter_carousel_slider#12]

**Comment by woshiyizhijiao** [comment]
能否添加 触摸轮播时禁止滑动的操作

**Comment by joelbrostrom** [comment]
Translation: Can I add a slide-free operation when I touch the carousel?

**Comment by serenader2014** [comment]
@joelbrostrom The OP's second comment means that he want to disable the auto play feature when he touched the carousel, which is implemented in `1.1.0` version.

@woshiyizhijiao You can try the latest version to test this feature. And for the zero length bug, you can temporary add a value check to avoid this problem. 你可以试一下最新版本，应该支持触摸时暂停自动播放的功能了。然后长度为0报错的问题，你可以先做个判断，如果长度为零则不调用这个组件。

**Comment by joelbrostrom** [comment]
Added in the 1.2.0 release.
