### ISSUE TITLE
disable manual scroll/slide

### ISSUE THREAD

**Issue by dhar619** [serenader2014/flutter_carousel_slider#121]
Hi, is there any option available to disable the manual scroll/slide when the automatic scroll is enabled? In short, I want to restrict the user to stop sliding the carousel when autoplay is true. Any example or snippet would be helpful.

**Comment by ehsanbigzad** [comment]
Set `scrollPhysics: NeverScrollableScrollPhysics()`.

**Comment by dhar619** [comment]
> 
> 
> Set `scrollPhysics: NeverScrollableScrollPhysics()`.

Thanks for the reply mate. It is working as required.
