### ISSUE TITLE
Flutter build/run --release crashes on startup with this package included

### ISSUE THREAD

**Issue by VinceERS** [serenader2014/flutter_carousel_slider#125]
I recently added carousel_slider: ^2.0.0 in place of carousel_pro, but have run into this problem where the app will work fine in debug mode but crash on startup in release.  I do not know how to see error output from release mode, but I have narrowed it down to just this package by commenting it out.

I am testing on a Pixel running Android 10.

flutter doctor -v:
```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.0 at /Users/corey/Documents/flutter
    • Framework revision d3ed9ec945 (10 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/corey/Library/Android/sdk/
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Pixel • FA71D0302387 • android-arm64 • Android 10 (API 29)

• No issues found!
```

It seems like this is the same issue other people are having here: https://github.com/flutter/flutter/issues/17896

I am wondering if maybe it is some problem with this package and newer versions of flutter on channel beta, unfortunately it is difficult for me to downgrade to channel stable at this time.

**Comment by serenader2014** [comment]
Hi @VinceERS ,thank you for reporting this issue.

I've tried to reproduce this issue in the example project, but it works without problem. Can you test the example project?

I have changed to the beta channel, and use `flutter run --release` mode to open the app, but it works.

**Comment by VinceERS** [comment]
Thanks, running `flutter run --release` in the example app did work for me.  It still does not work for me in my app.  There must be some setting somewhere that is conflicting but I'm not sure how to tell what is happening, adding internet permission to AndroidManifest.xml is not the problem.

I have tried following the steps relevant to me on this list: https://flutter.dev/docs/deployment/android

 I've tried `flutter clean`, `flutter pub cache repair`.

I am not using anything like `minifyEnabled` in my build.gradle, explicitly setting it to false does not do anything.  I do not use proguard.

I'm not sure what to try now.

**Comment by VinceERS** [comment]
This is odd, I was using that other package and ran into the same problem again.  I discovered that some bad exports in my package was causing this problem when using analysis options from effective dart.  In the end removing those exports was the problem, so I went back to this package and things are working fine.  I have no idea why commenting out this package was fixing my problem before but now this is solved and has nothing to do with this package that I can tell.

Thanks!

**Comment by vinnytwice** [comment]
Hi @VinceERS , could you please tell me what exports where your problem? My app also crashes only when in release moe, and thinking it was the package causing troubles I did design the carousel with PageView, but still the release mode crashing with bad state error message in Chrome console..
Thank you very much.

**Comment by VinceERS** [comment]
@vinnytwice Hello, unfortunately I don't think that information would be useful as the exports were particular to my internal project.  But to give you an idea, the project I was having this issue with was a flutter package that was imported into the main app.  This flutter package had exported many components which were unnecessary because the functionality required to be imported from the main app only accessed methods available in the main package file. 

Example package `package.dart`:

```
library my_package;

import 'methods_a.dart';
import 'methods_b.dart';

/// The following exports would be unnecessary as the main app doesn't call methods in these files:
/// export 'methods_a.dart';
/// export 'methods_b.dart';

class PackageWidget extends StatelessWidget {
...
}
```

Hopefully that makes sense to you as to the particular problem I was having.
