### ISSUE TITLE
The named parameter pauseAutoPlayOnTouch is not defined

### ISSUE THREAD

**Issue by DQvsRA** [serenader2014/flutter_carousel_slider#127]
After update to 2.0.0
![Screenshot 2020-04-17 at 12 57 23](https://user-images.githubusercontent.com/442111/79562283-16e39d00-80ab-11ea-80b4-e459debff2bf.png)

**Comment by serenader2014** [comment]
Yes, it has been removed in the v2.0.0. Please take a look at [changelog](https://github.com/serenader2014/flutter_carousel_slider/blob/master/CHANGELOG.md);

**Comment by DQvsRA** [comment]
@serenader2014 Ok, thanks for answer, but it's still in the docs:
<img width="807" alt="Screenshot 2020-04-17 at 13 27 32" src="https://user-images.githubusercontent.com/442111/79564613-4a282b00-80af-11ea-92fd-9f1b57b6690e.png">

**Comment by serenader2014** [comment]
@DQvsRA Thank you for pointing out. That's a mistake. Will fix it.
