### ISSUE TITLE
CarouselController methods fail when called inside onPageChanged

### ISSUE THREAD

**Issue by despie** [serenader2014/flutter_carousel_slider#128]
I wanted to create autoscrolling carousel with no infinite scroll. So when the carousel autoscrolls to the last position, I would like to animate it back to the starting position.
```
CarouselSlider(
    options: CarouselOptions(
          carouselController: controller,
          enableInfiniteScroll: false,
          autoPlay: true,
          reverse: false,
          onPageChanged: (index, reason) {
            if (index == carouselItems.length - 1) {
              controller.jumpToPage(0);
            }
          }),
      items: carouselItems,
);
```

Calling `jumpToPage` or `animateToPage` produce following error:
```
The following NoSuchMethodError was thrown while notifying listeners for AnimationController:
The getter 'pageController' was called on null.
Receiver: null
Tried calling: pageController

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      CarouselControllerImpl.jumpToPage (package:carousel_slider/carousel_controller.dart:63:39)
#2      ...
...
The AnimationController notifying listeners was: AnimationController#b1d43(▶ 57.181; for DrivenScrollActivity)
```

I saw the example with the button, but I need this jump to the beginning to happen automatically when carousel page autoscrolls to the end item.

This way the combination of `autoplay: true` and `enableInfiniteScroll: false` makes carousel to bounce the last item indefinitely.

Great work btw! Thanks!

**Comment by serenader2014** [comment]
hi @despie ,can you provide a more detailed demo? I've tried the code you provide, it works fine.

**Comment by despie** [comment]
Hi, sorry for the false alarm. It was my fault with wrong state management. It indeed works fine.
