### ISSUE TITLE
Autoplay when end is reached on no infinite scroll carousel

### ISSUE THREAD

**Issue by despie** [serenader2014/flutter_carousel_slider#129]
The combination of `autoplay: true` and `enableInfiniteScroll: false` makes carousel to bounce the last item indefinitely.

It would be nice if either carousel animates to the start and continues autoplay or carousel continues autoscrolling in reverse in this case.

**Comment by serenader2014** [comment]
Hi @despie ,this is a known issue, and I've fixed it in the `feature/v2` branch. The feature branch will be merged to master in next couple days, so if you're in a hurry to fix this bug, you can now use the `feature/v2` branch.

**Comment by serenader2014** [comment]
Fixed in v2.1.0, please give it a try.
