### ISSUE TITLE
calling SetState in parent widget is breaking CarouselController

### ISSUE THREAD

**Issue by lukecaan** [serenader2014/flutter_carousel_slider#135]
Hi, 

I've got a Stateful parent widget which stores an assortment of things, and then a child Stateless widget which my carousel lives inside. I'm only using the CarouselController (which is a property of the stateless widget) to move between pages. The CarouselController works perfectly until the Parent's setState method gets called. Once that setState method has been called, the following `nextPage` or `previousPage` call on the CarouselController creates the error shown below. 

Am I doing something wrong? I'm probably making a noobie mistake sorry I am new to Flutter but I can't find any information that would explain it!

![image](https://user-images.githubusercontent.com/14064888/80479251-1512b700-8992-11ea-8ab2-fe55479e9399.png)

**Comment by serenader2014** [comment]
Hi, can you provide a reproducible demo?
