### ISSUE TITLE
How to pause auto play?

### ISSUE THREAD

**Issue by LoveAndroDev** [serenader2014/flutter_carousel_slider#143]
Hi

How can we pause autoplay so that while carousel is out of screen or to say out of visibility it will automatically pause or any method to pause it....?

**Comment by serenader2014** [comment]
Hi @LoveAndroDev , currently the plugin doesn't support manually pause the auto play, but I think it's worth to add a method in the `CarouselController`. Will trying to implement this feature if I have time. Also PR is always welcome :)

**Comment by LoveAndroDev** [comment]
Thanks :)

**Comment by thearthurdev** [comment]
@serenader2014 with the PR I have submitted you can now pause and play autoplay.

@LoveAndroDev once it is merged, simply assign a variable to the `autoplay` parameter in `carouselOptions` and change that to pause and play the carousel.

**Comment by LoveAndroDev** [comment]
Ok thanks i will try it for sure when available

**Comment by thearthurdev** [comment]
Sure. I went further to add `startAutoPlay` and `stopAutoPlay` as methods in the `CarouselController` class. This is a better way to play and pause the carousel on demand.

Hopefully it get's merged, and soon

**Comment by LoveAndroDev** [comment]
Yes this is something i am looking for it help to disable autoplay animation while not requried like when slider is out of visibility.
Thanks ✌✌✌✌

**Comment by yiky84119** [comment]
hello, any news about this?

**Comment by thearthurdev** [comment]
Not yet. The author seems to be away. I don't know whether you can fork my fork but you'll find all the changes here 

https://github.com/thearthurdev/flutter_carousel_slider

Here's a guide on how to use an unpublished dependancy
https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

Hope this helps

**Comment by nicolasvahidzein** [comment]
I second this feature, can we contact the author and ask him to merge this soon please? This would be very welcomed.

**Comment by nicolasvahidzein** [comment]
Hello i tried this but it's querying forever. Let me know if i missed something.

Thanks.

```
  carousel_slider:
    git:
      url: https://github.com/thearthurdev/flutter_carousel_slider
```

**Comment by thearthurdev** [comment]
Hello @nicolasvahidzein, try this syntax instead:
```
 carousel_slider:
    git: git://github.com/thearthurdev/flutter_carousel_slider
```
I hope it works

**Comment by nicolasvahidzein** [comment]
@thearthurdev funny enough my https links works and your git link doesn't. I get the start and stop functionality.

Can you please check on your end to see if you can bypass the repo using the git link or it freezes too. Very strange.

**Comment by thearthurdev** [comment]
@nicolasvahidzein that's odd... I tested my response and it worked. I guess both links work under different circumstances, which I have no idea about.

**Comment by DeliriousLee** [comment]
```dart
  @override
  void didUpdateWidget(CarouselSlider oldWidget) {
    carouselState!.options = options;
    carouselState!.itemCount = widget.itemCount;

    // pageController needs to be re-initialized to respond to state changes
    pageController = PageController(
      viewportFraction: options.viewportFraction,
      initialPage: carouselState!.realPage,
    );
    carouselState!.pageController = pageController;

    // line:102, delete this line.because this will call create timer function again
    handleAutoPlay();

    super.didUpdateWidget(oldWidget);
  }
```


you can fix this issue,by delete line 102 
```dart
handleAutoPlay();
```
in 'carousel_slider/carousel_slider.dart' file
