### ISSUE TITLE
Disable scrolling

### ISSUE THREAD

**Issue by JulienDupontDev** [serenader2014/flutter_carousel_slider#144]
Hello,

I would like to know if it's possible to disable scrolling by end user because I use this carousel to display items that shouldn't be scrolled by user. 
If the feature is not available, could it be possible to implement it ? 

Thank you

**Comment by serenader2014** [comment]
Hi @JulienDupontDev , in order to disable scrolling, you can pass `scrollPhysics: NeverScrollableScrollPhysics()` to `CarouselOptions`.

**Comment by JulienDupontDev** [comment]
> Hi @JulienDupontDev , in order to disable scrolling, you can pass `scrollPhysics: NeverScrollableScrollPhysics()` to `CarouselOptions`.

Thank you !
