### ISSUE TITLE
Different layout after v2 update

### ISSUE THREAD

**Issue by enricobenedos** [serenader2014/flutter_carousel_slider#146]
Good morning,
after I've update the library to the new `v2.0.1` version I noticed a different layout in the carousel using the same code. It seems that the gap/blank space between image has been increased.
`v1.4.1`:
```dart
CarouselSlider.builder(
                  autoPlay: true,
                  pauseAutoPlayOnTouch: const Duration(seconds: 10),
                  enlargeCenterPage: true,
                  aspectRatio: 2.0,
                  itemCount: _tourImages.length,
                  itemBuilder: (BuildContext context, int itemIndex) =>
                      ClipRRect(
                    borderRadius: BorderRadius.all(Radius.circular(12.0)),
                    child: CachedNetworkImage(
                      imgUrl: _tourImages[itemIndex],
                      canShowFullScrenn: true,
                    ),
                  ),
                ),
```
![image](https://user-images.githubusercontent.com/12233746/81230531-f0ea5200-8ff1-11ea-933e-00659ef82724.png)

`v2.0.1`:
```dart
CarouselSlider.builder(
                  options: CarouselOptions(
                    autoPlay: true,
                    enlargeCenterPage: true,
                    aspectRatio: 2.0,
                  ),
                  itemCount: _tourImages.length,
                  itemBuilder: (BuildContext context, int itemIndex) =>
                      ClipRRect(
                    borderRadius: BorderRadius.all(Radius.circular(12.0)),
                    child: CachedNetworkImage(
                      imgUrl: _tourImages[itemIndex],
                      canShowFullScrenn: true,
                    ),
                  ),
                ),
```
![image](https://user-images.githubusercontent.com/12233746/81230602-15dec500-8ff2-11ea-9796-993d826224d1.png)

Is it possible to reduce it? Is it an expected behaviour?

**Comment by serenader2014** [comment]
Hi @enricobenedos , can you post a more detailed example?

**Comment by enricobenedos** [comment]
Hey @serenader2014, thank you for your fast reply. 
It is crazy but I'm not able to reproduce it in a new project. I'm trying to do that at the moment but no results for now. In my production app changing the major version of library introduce the strange behaviour you can see. It seems like `aspectRatio` or something in the widgets tree works differently from `v1.x.x`, this cause more blank space between images that in my opinion results in a worst carousel.

**Comment by serenader2014** [comment]
@enricobenedos if you're upgrading to v2.1.0, then it maybe because we've changed the `Sizedbox` to `Transform.scale` in the carousel item wrapper.

**Comment by enricobenedos** [comment]
I think this change can be a problem. But the crazy thing is that I'm not able to reproduce it. For now I'm constrained to use `v1.4.1`. I will investigate more as soon as possible.

**Comment by pbysh** [comment]
I have just updated and am dismayed to find the space between my carousel items has increased and there doesn't seem to be an option to control that.

**Comment by enricobenedos** [comment]
Hey @pbysh, are you able to reproduce it in a sample project?

**Comment by pbysh** [comment]
Sure, this is a sample project using carousel_slider 1.4.1:

```
import 'package:flutter/material.dart';
import 'package:carousel_slider/carousel_slider.dart';
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class SampleCard extends StatelessWidget {
  final String title;
  const SampleCard({Key key, @required this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Card(
        elevation: 5,
        child: Container(
          width: double.infinity,
          child: Column(
            children: <Widget>[
              Container(child: Text(this.title))
            ],
          ),
        )
      ),
    );
  }
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    List<Widget> cardItems = [
      SampleCard(title: "Card 1"),
      SampleCard(title: "Card 2"),
      SampleCard(title: "Card 3"),
      SampleCard(title: "Card 4"),
      SampleCard(title: "Card 5"),
      SampleCard(title: "Card 6"),
    ];

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: CarouselSlider(
          items: cardItems,
          autoPlay: false,
          height: 130,
          enlargeCenterPage: true,
          aspectRatio: 2.0,
          viewportFraction: 0.9,
        ),
      ),
    );
  }
}
```

The output of this looks like this:

![Screenshot_20200521-143918](https://user-images.githubusercontent.com/418716/82609630-b8aa4e00-9b71-11ea-9f57-499e0a10c7aa.png)

Updating to carousel_slider 2.1.0 and updating the CarouselSlider bits to this:

```
        child: CarouselSlider(
          items: cardItems,
          options: CarouselOptions(
            autoPlay: false,
            height: 130,
            enlargeCenterPage: true,
            aspectRatio: 2.0,
            viewportFraction: 0.8,
          ),
        )
```

Results in this:

![Screenshot_20200521-144044](https://user-images.githubusercontent.com/418716/82609639-bfd15c00-9b71-11ea-995f-3b494da4f26d.png)
![Screenshot_20200521-144108](https://user-images.githubusercontent.com/418716/82609648-c233b600-9b71-11ea-820e-f51fa410c485.png)

The first screenshot shows it with `viewportFraction` of 0.9 as I had it before, where you can't even see the neighboring cards anymore. The next one changes it 0.8, where as you can see the gap between the cards is much wider now.

**Comment by serenader2014** [comment]
Hi @enricobenedos , I have added a new option to allow user to choose which enlarge strategy to use when enlarging the center page. Please upgrade to v2.2.0 and give it a try.

I'm closing this issue, but if you have any further issues, feel free to reopen it.

**Comment by enricobenedos** [comment]
Hey @serenader2014 I will test your release as soon as possible to provide you a feedback 😃

**Comment by enricobenedos** [comment]
Hi @serenader2014, using `enlargeStrategy: CenterPageEnlargeStrategy.height` I solve this issue perfectly. 
Thank you!

**Comment by FNPCMDs** [comment]
> Hi @serenader2014, using `enlargeStrategy: CenterPageEnlargeStrategy.height` I solve this issue perfectly.
> Thank you!

Hi, can you share your code? When I use `enlargeStrategy: CenterPageEnlargeStrategy.height`, no card get enlarger
