### ISSUE TITLE
Item doesn't have rounded borders

### ISSUE THREAD

**Issue by amith-patil** [serenader2014/flutter_carousel_slider#147]
is there anyway to have rounded borders? I put a container as an item with rounded borders, but the item shows a white color around the rounded borders. this also affects when the background is a darker color. 
![Screenshot_1588874780](https://user-images.githubusercontent.com/51911194/81329059-9289a600-90bb-11ea-9851-ac07dce622fd.png)

**Comment by amith-patil** [comment]
this is my item

` Padding(
                    padding: const EdgeInsets.symmetric(vertical: 50),
                    child: Material(
                      elevation: 10,
                      child: Container(
                        width: _width,
                        decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(50),
                            color: Colors.blue,
                        image: DecorationImage(
                          image: NetworkImage('https://www.itl.cat/pngfile/big/30-302874_hd-cover-dark-forest-wallpapers-high-quality-wallpapers.jpg'),
                          fit: BoxFit.cover,
                        )),
                      ),
                    ),
                  ),`

**Comment by amith-patil** [comment]
``` Padding(
                    padding: const EdgeInsets.symmetric(vertical: 50),
                    child: Material(
                      elevation: 10,
                      child: Container(
                        width: _width,
                        decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(50),
                            color: Colors.blue,
                        image: DecorationImage(
                          image: NetworkImage('https://www.itl.cat/pngfile/big/30-302874_hd-cover-dark-forest-wallpapers-high-quality-wallpapers.jpg'),
                          fit: BoxFit.cover,
                        )),
                      ),
                    ),
                  ),```

**Comment by amith-patil** [comment]
nevermind, I'm dumb.

**Comment by Shahmirzali-Huseynov** [comment]
@amith-patil  how fixed?
