### ISSUE TITLE
How can i show images with a full width?

### ISSUE THREAD

**Issue by nerdrun** [serenader2014/flutter_carousel_slider#154]
Hello,
I'm making my app with your lovely plugin and mostly it works as I expected like below:
![image](https://i.imgur.com/Fchn25M.png)

But I have faced a problem that showing the previous and the next images not only the current image. I actually want to show the current image with a full display.

I tried all your params but I couldn't make it.. :((

This is my a part of code.

```dart

CarouselSlider.builder( 
  carouselController: _carouselController,
  options: CarouselOptions(
    initialPage: _initialPage,
    height: 320,
    onPageChanged: (int number, CarouselPageChangedReason reason) => _initialPage = number,
  ),
  itemCount: images.length,
  itemBuilder: (BuildContext context, int itemIndex) {
    return Container(
      width: MediaQuery.of(context).size.width,
      decoration: BoxDecoration(
        image: DecorationImage(
          fit: BoxFit.cover,
          colorFilter: ColorFilter.mode(Colors.black.withOpacity(0), BlendMode.overlay),
          image: NetworkImage(
            images[itemIndex]['link'],
          )
        )
      ),
    );
  },
),
```

Could you help me?

**Comment by kencochrane** [comment]
Have you tried setting the `viewportFraction` option to `1.0` in CarouselOptions?

```
viewportFraction: 1.0,
```

**Comment by nerdrun** [comment]
I found my terrible mistake.
I wrapped CarouselSlider with Column so that it couldn't get a full width.
Now i've solved this problem. thank you so much!
