### ISSUE TITLE
Feature: Page Snapping

### ISSUE THREAD

**Issue by ram231** [serenader2014/flutter_carousel_slider#158]
Since the Carousel Slide uses PageView.builder, it would be better to have an option to enable/disable page snapping. Thanks!

**Comment by xingfudeshi** [comment]
I need this option too.

**Comment by DFelten** [comment]
I've made a pull request with an option to disable snapping: https://github.com/serenader2014/flutter_carousel_slider/pull/202

**Comment by serenader2014** [comment]
Added in #202 and published in v2.3.0

**Comment by xingfudeshi** [comment]
> Added in #202 and published in v2.3.0

Thanks man

**Comment by xingfudeshi** [comment]
> I've made a pull request with an option to disable snapping: https://github.com/serenader2014/flutter_carousel_slider/pull/202

Thanks man
