### ISSUE TITLE
[weird issue] autoPlay causes re-call class functions !

### ISSUE THREAD

**Issue by Ess-Soft** [serenader2014/flutter_carousel_slider#16]
**Steps to Reproduce**

I'm calling the code below to show Carousel with auto play and when image automatically slides `autoPlay: true` this calls a firebase firestore method that loads some data to my app
``` Dart
CarouselSlider carousel(BuildContext context) {
    return CarouselSlider(
      items: Flutkart.imgList.map((url) {
        return Container(
          margin: EdgeInsets.all(0.0),
          child: Stack(
            children: <Widget>[
              Center(child: CircularProgressIndicator()),
              ClipRRect(
                borderRadius: BorderRadius.all(Radius.circular(0.0)),
                child: Image.network(
                  url,
                  fit: BoxFit.cover,
                  height: 300,
                  width: MediaQuery.of(context).size.width,
                ),
              ),
            ],
          ),
        );
      }).toList(),
      viewportFraction: 1.0,
      aspectRatio: 1.0,
      autoPlay: true,
      updateCallback: (index) {
        setState(() {
          _selectedImgIndex = index;
        });
      },
    );
  }
```
so when the image automatically slides the method below is re-called:
``` Dart
Stream getCollectionStream() {
    print('getReviewsStream: called');
    return fireStore
        .collection('myCollection')
        .where('something', isEqualTo: 'somethingelse')
        .snapshots();
  }
```

so everytime the image slides the `getCollectionStream()` is called 
in every image slide i get this log  in my console

> I/flutter (29008): getReviewsStream: called
I/flutter (29008): getReviewsStream: called
I/flutter (29008): getReviewsStream: called
I/flutter (29008): getReviewsStream: called
I/flutter (29008): getReviewsStream: called

PS: even if i set autoPlay to false and slide the image manually the `getCollectionStream()` is called again.

How can we solve this problem ??
Thank you for this awesome package :)

**Comment by Ess-Soft** [comment]
Yes exactly the `updateCallback` causes the widget tree to rebuild
but how can i get the carousel selected index without causing the tree to rebuild ?
**this code causes widget tree to rebuild:**
``` Dart
 updateCallback: (index) {
        setState(() {
          _selectedImgIndex = index;
        });
      },
```
if i removed the `setState()` then `_selectedImgIndex` so how this could be solved ? thank you.

**Comment by serenader2014** [comment]
Since there is very limited code in your provided information, what I can suggest is that don't call `getCollectionStream` function in your widget's `build` method, and that should be ok, even if you call `setState` in `updateCallback` callback.
