### ISSUE TITLE
Janks on carousel scroll in 2.1.0 after Transform.scale change

### ISSUE THREAD

**Issue by romanlytvyn** [serenader2014/flutter_carousel_slider#161]
Hi,

After `SizedBox` -> `Transform.scale` change in the latest release (`2.1.0`) we have noticed a drastic performance degradation during carousel scroll animation.
It used to be butter smooth and now it janks on every page change.
The problem goes away if `enlargeCenterPage` is set to `false` and the issue was not present in `2.0.0`.

It can be easily reproduced by putting a lot of widgets (text, icons, images) on the carousel page.

Additionally we have a `Text` widget wrapped in `SingleChildScrollView` and `Expanded` and height change gave a cool animation with extra text appearing as central page was scrolled into view.

Would it be possible to introduce an option to choose which strategy to use for enlarging the center page: `height` or `scale` ?

**Comment by serenader2014** [comment]
Hi @romanlytvyn , thank you for your advice, I've added a new option called `enlargeStrategy` in v2.2.0, please have a try.

And I'm closing this issue, if you have further questions, feel free to reopen it.

**Comment by romanlytvyn** [comment]
Updated to the latest version and the new `enlargeStrategy` option works like a charm! Many thanks, @serenader2014!
