### ISSUE TITLE
onPageChanged with manual reason is called randomly while using carouselController

### ISSUE THREAD

**Issue by MartinJLee** [serenader2014/flutter_carousel_slider#165]
The issue isn't easy to reproduce.
I'm changing the page using carouselController.
Also allowing user to change page manually.
Sometimes when I change the carousel to an item.
_carouselPageChanged called to a random index (I guess an item between current item and next item) with reason manual.

below is my _carouselPageChanged
``` dart
  _carouselPageChanged(int index, CarouselPageChangedReason reason) {
    if (reason != CarouselPageChangedReason.manual) return;
    final id = _ids[index];
    if (id != null) {
      // TODO FIX sometime called while carousel is animating to other item
      _handleItemChange(id);
    } else {
      // TODO handle unexpected error
    }
  }

```

**Comment by Dohmanlechx** [comment]
I can reproduce this while first clicking on the item itself first. Looks like this plugin gets confused by then because you had touched the item, so it thought you swiped it manually.

**Comment by Dohmanlechx** [comment]
```
  void onPanDown() {
    if (widget.options.pauseAutoPlayOnTouch) {
      clearTimer();
    }

    mode = CarouselPageChangedReason.manual;
  }
```

Found the culprit. It would be nice if it was only manual if it was a swipe movement, not a tap.

**Comment by Dohmanlechx** [comment]
Bumped from `2.1.0` to `2.2.1` and the issue vanished :) I checked the source code but didn't understand how it could be fixed tho.

**Comment by MartinJLee** [comment]
> Bumped from `2.1.0` to `2.2.1` and the issue vanished :) I checked the source code but didn't understand how it could be fixed tho.

Thank you for the finding. It seems the issue now fixed.

**Comment by MartinJLee** [comment]
@Dohmanlechx Can you tell me now to compare changes between two versions?

**Comment by Dohmanlechx** [comment]
@MartinJLee I just clicked on the class `CarouselSlider` and searched for `.manual` in that file.

**Comment by MartinJLee** [comment]
@Dohmanlechx Thank you for the reply. The reason why I'm asking is that I noticed the other behavior change after upgrade to 2.2.1.
with 2.2.1, I cannot manually swipe to the last item from the first item even if 'enableInfiniteScroll' is set to true. Weird enough I can swipe from the last item to the first item, although the other issue(#164) I have reported still there.

**Comment by Dohmanlechx** [comment]
@MartinJLee Are you sure that you remembered to subtract with 1? Like `animateTo(items.length - 1);`

**Comment by MartinJLee** [comment]
@Dohmanlechx I'm keeping the other keys in a separate list
``` dart
final List<String> _ids = [];
...
        final index =
            _ids.lastIndexWhere((element) => element == state.id);
        if (index != null) {
          _carouselController.animateToPage(index);
        }

```

**Comment by Dohmanlechx** [comment]
Well, now you are not scrolling to the last item as you wrote. You are scrolling to the last item which still meets the condition. Please try using `_carouselController.animateToPage(_ids.length - 1);` and spam it to see if it is working good. If your index actually isn't null and is within 0 to `_ids.length - 1` then I don't know why it doesn't work and hope the devs will see this soon.

**Comment by MartinJLee** [comment]
@Dohmanlechx Thank you for the response.
Relate to the 
> I cannot manually swipe to the last item from the first item even if 'enableInfiniteScroll' is set to true.
The issue is solved after I stop the debugger and rebuilt the source.
