### ISSUE TITLE
2.2.0 can not find the class CarouselOptions

### ISSUE THREAD

**Issue by wwl901215** [serenader2014/flutter_carousel_slider#168]
Hi, we update the version to 2.2.0, then we found the CarouselOptions can not find;

**Comment by naumanmir** [comment]
@wwl901215 i guess your import of library is missing.

**Comment by ram231** [comment]
that was a breaking changes from the API(implementation). please do inform us ahead or at the least, update the README.md. Thanks for the new update!

**Comment by wwl901215** [comment]
> @wwl901215 i guess your import of library is missing.

i find that it need import alone,  suggest create a single file for export what needed export, then we do not change our code if you change your class place;
like this:
export 'xxx/xxx';
export 'xxx/xxx;
export 'xxx/xxx;

**Comment by welshcathy** [comment]
Please update https://pub.dev/packages/carousel_slider#-readme-tab- 
with the new import requirements
import 'package:carousel_slider/carousel_slider.dart';
import 'package:carousel_slider/carousel_options.dart';  << new and undocumented right now

**Comment by serenader2014** [comment]
Hi @welshcathy , @ram231 , @wwl901215 , sorry for the inconvenience, that is indeed my mistake, I have published a new version which will export the carousel_options and carousel_controller by default, so you can upgrade to v2.2.1 to try it out.
