### ISSUE TITLE
Call for proper documentation

### ISSUE THREAD

**Issue by thedejifab** [serenader2014/flutter_carousel_slider#17]
This is a very fantastic library for implementing the carousel but there are no doc comments. The library's users would feel way better if docs are included to know the function of each attribute

**Comment by serenader2014** [comment]
You're right about this. Will add this in next release.

**Comment by joelbrostrom** [comment]
This should be fixed now :)

**Comment by serenader2014** [comment]
Documentation added in the v1.1.0 version.
