### ISSUE TITLE
Error: The method 'CarouselOptions' isn't defined for the class

### ISSUE THREAD

**Issue by Arcturus5404** [serenader2014/flutter_carousel_slider#170]
I get the following error on the 2.2.0 version of this awesome flutter widget.

Seems to be working just fine with 2.0.0 and 2.1.0. 

it gives me compile errors on:

       options: CarouselOptions(
                onPageChanged: (page, reason) => setInkResult(page),
                enlargeCenterPage: true,
                enableInfiniteScroll: false,
                viewportFraction: 1.0,
                initialPage: widget.colors.indexOf(widget.inkResult),
              ))

**Comment by Surio89** [comment]
you need

`import 'package:carousel_slider/carousel_options.dart';`

since 2.2.0

**Comment by serenader2014** [comment]
Hi @Arcturus5404 , sorry for the inconvenience, that is indeed my mistake, I have published a new version which will export the `carousel_options` and `carousel_controller` by default, so you can upgrade to `v2.2.1` to try it out.

**Comment by Arcturus5404** [comment]
Thanks! It is working again! Apologies for the late feedback.

**Comment by tolotrasamuel** [comment]
how to import carousel_controller ? CarouselController is an abstract class
