### ISSUE TITLE
state is null while trying to call jumpToPage

### ISSUE THREAD

**Issue by elsheikhmahmoud** [serenader2014/flutter_carousel_slider#175]
Dart Error: Unhandled exception:
NoSuchMethodError: The getter 'options' was called on null.
Receiver: null
Tried calling: options

**Comment by Tristan1075** [comment]
Same here 👍

**Comment by nguyendai0208** [comment]
Me too!

**Comment by nguyendai0208** [comment]
Don't jump to next page when I use
CarouselSlider.builder(
 itemCount: ,
 itemBuilder:,
options:
)
but It work with 
CarouselSlider(
                  items: ,
                  options:
                  CarouselOptions(enlargeCenterPage: true, height: 200),
                  carouselController: _carouselController,
                ),

**Comment by Tristan1075** [comment]
Hey i found out what's wrong, i think it's because your widget needs to be stateful, see example :) 

Now it works ! 

https://github.com/serenader2014/flutter_carousel_slider/blob/master/example/lib/main.dart

**Comment by ThomRI** [comment]
I can't seem to get it working, and keep having the same error. I tested the package in a simple project with a button supposed to trigger the controller's next page. I have attached the main.dart as well as my pubspec :
[test_carousel.zip](https://github.com/serenader2014/flutter_carousel_slider/files/4907367/test_carousel.zip)

The error is the same 
`Unhandled Exception: NoSuchMethodError: The getter 'options' was called on null. ; 
Receiver: null ; 
Tried calling: options`

I have tried it on Android Studio 4.0 running on Windows 10 and USB Debugging on my ASUS Z01RD.
Any help would be appreciated, thanks ! (:

**Comment by Selecao** [comment]
Guys i found solution!

Use `controller` that NOT inside `options` field:

```
CarouselSlider(
        items: child,
        carouselController: myCarouselController, // use This
        options: CarouselOptions(
        // some options here
       // carouselController: myCarouselController, // this one Do Not Work
      ),
),
```

**Comment by Zfinix** [comment]
> Guys i found solution!
> 
> Use `controller` that NOT inside `options` field:
> 
> ```
> CarouselSlider(
>         items: child,
>         carouselController: myCarouselController, // use This
>         options: CarouselOptions(
>         // some options here
>        // carouselController: myCarouselController, // this one Do Not Work
>       ),
> ),
> ```

It worked but why do we have it under options too, i think the docs need to be updated to show this use case

**Comment by emmett-deen** [comment]
Docs definitely should be updated to reflect this!

**Comment by Scott1803** [comment]
> Guys i found solution!
> 
> Use `controller` that NOT inside `options` field:
> 
> ```
> CarouselSlider(
>         items: child,
>         carouselController: myCarouselController, // use This
>         options: CarouselOptions(
>         // some options here
>        // carouselController: myCarouselController, // this one Do Not Work
>       ),
> ),
> ```

Thank you so much, it was getting really annoying, and your solution worked!
