### ISSUE TITLE
interval between auto display of images cannot be changed from 4 seconds

### ISSUE THREAD

**Issue by BitKnitting** [serenader2014/flutter_carousel_slider#18]
The code has this.interval: const Duration(seconds: 4), Shouldn't interval be something that can be set?

**Comment by BitKnitting** [comment]
The code has ``` this.interval: const Duration(seconds: 4),``` Shouldn't interval be something that can be set?

**Comment by serenader2014** [comment]
`this.interval: const Duration(seconds: 4)` this means that `this.interval` 's default value is 4 seconds, however you can override this value by passing a new value in the class's params:

```dart
  CarouselSlider(
    items: imgList.map((url) {
      return Container(
        margin: EdgeInsets.all(5.0),
        child: ClipRRect(
          borderRadius: BorderRadius.all(Radius.circular(5.0)),
            child: Image.network(url,
            fit: BoxFit.cover,
            width: 1000.0,
          )
        )
      );
    }).toList(),
    viewportFraction: 0.9,
    aspectRatio: 2.0,
    autoPlay: true,
    interval: const Duration(seconds: 1)
  )
```
