### ISSUE TITLE
Contribute pause auto play on user input

### ISSUE THREAD

**Issue by joelbrostrom** [serenader2014/flutter_carousel_slider#19]
Hi, I added a pause on user input feature that pause the auto play animation a set amount of time letting the user interact with a screen without it scrolling to the next widget.

I can create a PR if you want to add it to the repo.

Commit notes 

Added a variable `pauseOnUserImput` which takes a `Duration`.
 
If `autoPlay` is set to true and `pauseOnUserInput` is not null, the 
`PageView` will be wrapped in a `GestureDetector` listening for
pan gestures.

Premise: 
When using a sliding carousel you might want the 
user to be able to interact with a slide.
For now, the user can swipe back if he/she see something they
like, but the carousel will keep iterating through its children.
This forces the user to constantly swipe back to the page they
were interacting with.

For example, imagen a commercial display rolling adds in a 
waiting room. If something interest a person he or she might 
want to pause the slide to read all the information.

This feature lets the developer implement a way too pause the
auto play feature for a set amount of time, resetting each time 
new input is detected.
This way the user can interact with the application and after they
leave it will go back to circling the widgets.

**Comment by serenader2014** [comment]
Thank you for your contribution, a PR is always welcome!

**Comment by joelbrostrom** [comment]
Done :)

My linting settings were not compatible with yours, so I had to format the code manually.
If you accept the PR you should probably reformat it on your machine.

**Comment by serenader2014** [comment]
PR is merged, thank you for your contribution.
