### ISSUE TITLE
initialPage isn't working in current version

### ISSUE THREAD

**Issue by varundroid** [serenader2014/flutter_carousel_slider#2]
I had to do the following to fix the issue - 

`pageController = new PageController(
      viewportFraction: viewportFraction,
      initialPage: initialPage
 );`

instead of - 

`pageController = new PageController(
      viewportFraction: viewportFraction,
      initialPage: realPage
 );`

but now it has stopped loading the image for me and carousel isn't working as expected. I am still trying to fix it.

**Comment by serenader2014** [comment]
Hello, sorry for the late response. I've fix this bug in v0.0.5, please try again.

Also noted, currently the package in pub.dartlang.org is still in v0.0.4, I can not publish my package to the pub, I have open an issue on the pub's GitHub repo. In the meantime you can only install this package using git url. Sorry for the inconvenience.

**Comment by serenader2014** [comment]
The package is published to the pub.dartlang.org, and I'm closing this issue since there is no response after my last comment.
