### ISSUE TITLE
Exception caught by widgets library Null check operator used on a null value

### ISSUE THREAD

**Issue by haleyhuynh** [serenader2014/flutter_carousel_slider#203]
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following _CastError was thrown building AnimatedBuilder(animation: PageController#7043e(one client, offset 3312000.0), dirty, state: _AnimatedState#59a62):
Null check operator used on a null value

The relevant error-causing widget was: 
  CarouselSlider file:///Volumes/Work/SAM/sam_app/lib/src/ui/pages/intro.dart:57:9
When the exception was thrown, this was the stack: 
#0      ScrollPosition.minScrollExtent (package:flutter/src/widgets/scroll_position.dart:137:49)
#1      CarouselSliderState.build.<anonymous closure>.<anonymous closure> (package:carousel_slider/carousel_slider.dart:263:57)
#2      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1483:19)
#3      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:179:48)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4758:27)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was: 
  CarouselSlider file:///Volumes/Work/SAM/sam_app/lib/src/ui/pages/intro.dart:57:9
════════════════════════════════════════════════════════════════════════════════════════════════════

```
How can I fix this issue?

**Comment by Sammius** [comment]
Perhaps this is due to these changes in Flutter:
https://github.com/flutter/flutter/issues/66030

**Comment by duttaoindril** [comment]
No, this is caused by the new NNBD code in flutter, apparently 4 days old (master branch)

![image](https://user-images.githubusercontent.com/4969854/93690339-02f1fc00-fa8c-11ea-8de7-4941de455639.png)

Is this flutter's fault or this library's implementation fault?

I'm also getting this error for this package: https://pub.dev/packages/flutter_swiper

**Comment by Badman12** [comment]
Very stupid fix but for me it works very well as a temp solution https://github.com/Badman12/flutter_carousel_slider/commit/1101af6921f22d0167446cf9d233e9ba4b14fc0f

**Comment by imJithin777** [comment]
Does anyone have a solution for "Null check operator used on a null value"this. Please provide if any.

**Comment by oscarlindenbaum** [comment]
@imJithin777 

Temporary Solution - add this to your `pubspec.yaml

```yaml
dependency_overrides:
  carousel_slider:
    git: https://github.com/oscarlindenbaum/flutter_carousel_slider
```

**Comment by viniciusfdev** [comment]
I am having the same issue using the package.

flutter version: Flutter 1.22.0-10.0.pre.364
dart version: Dart 2.11.0
carousel_slider version: 2.2.1

I checked the temporary solution from  @oscarlindenbau
and it worked for  me, thanks about that.
I am hoping this get fix. 
Thanks for the Package as well!

**Comment by serenader2014** [comment]
The issue is solved by using @Badman12 's solution. Please upgrade to the latest version and try it again.

**Comment by IsraRM93** [comment]
![image](https://user-images.githubusercontent.com/87777674/195713390-0bf8b0ef-dab1-4427-82ae-8cd548dcf89d.png)
me sales este error tambien
