### ISSUE TITLE
[Feature] : Get the current slide position 

### ISSUE THREAD

**Issue by loicsacre** [serenader2014/flutter_carousel_slider#209]
It would be great to have the possibility to get the current position of the carousel through the CarouselController.

**Comment by alexandrebeato** [comment]
You did it? How?

**Comment by loicsacre** [comment]
You can simply use the `onPageChanged` callback from the `CarouselOptions`
```
options: CarouselOptions(
 onPageChanged: (index, reason) {
   // this is the current index 
  },
 ),
```

**Comment by enricobenedos** [comment]
Cannot be a good idea to retrieve it also using the available controller?

**Comment by loicsacre** [comment]
@enricobenedos Because there is no mean to retrieve it from there (see https://github.com/serenader2014/flutter_carousel_slider/blob/master/lib/carousel_controller.dart) or I missed it. I think it is ok to get the index with the onChanged() method
