### ISSUE TITLE
Any plan to support vertical scroll carousel?

### ISSUE THREAD

**Issue by showgp** [serenader2014/flutter_carousel_slider#21]

**Comment by serenader2014** [comment]
Already merged you PR, but still have some issues to be fixed. Currently the `enlargeCenterPage` option is not working, because the code is not compatible with vertical pageview.

Will take a look at this when I have time. And PR is always welcome.

**Comment by showgp** [comment]
I made a fix on it, `enlargeCenterPage` should working with vertical scroll carousel now. 

Sorry for that.

**Comment by joelbrostrom** [comment]
Added in 1.2.0
