### ISSUE TITLE
How to remove the space on left and align right below the text 'label'

### ISSUE THREAD

**Issue by willladislaw** [serenader2014/flutter_carousel_slider#214]
Remove the whitespace on the left and move all further to the left so that "Option" is aligned right below "label" and "Option 2" clearly visible on screen, if `viewportFraction =1` is set,  this causes "Option 2" to disappear off screen which is to be expected. 
```
    return CarouselSlider(
      options: CarouselOptions(
        disableCenter: true,
        enableInfiniteScroll: false,
        enlargeCenterPage: false,
        height: 40,
        viewportFraction: .4,
      ),
      items: widgetList.map((i) {
        return Builder(
          builder: (BuildContext context) {
            return Container(
              alignment: Alignment(-10,0),
              padding: EdgeInsets.all(5),
              child: i,
            );
          },
        );
      }).toList(),
    );


List<Widget> widgetList(){
    return [
        Material(
          type: MaterialType.transparency,
          child: Ink(
            decoration: BoxDecoration(
              border: Border.all(color: Colors.black, width: 1.0),
              color: Colors.white,
            ),
            child: Center(
              child: InkWell(
                onTap: (){},
                child: Text('Option')),
            ),
          ),
        ),
      ...
      ];
  }
```
<img width="410" alt="Screenshot 2020-10-18 at 22 47 39" src="https://user-images.githubusercontent.com/22636642/96386611-28aa1800-1194-11eb-92cb-b855556ddfbf.png">

**Comment by Abdullah-Zakhoi** [comment]
@willladislaw please add `widget list ` to see what are the properties of the label text and option button

**Comment by willladislaw** [comment]
Replaced with ListView

**Comment by callmejm** [comment]
@willladislaw Hi, may I know how you solve this ? how to replace to ListView ? thanks

**Comment by Nei1eveN** [comment]
@callmejm he replaced the carousel usage with `ListView`, then set the `scrollDirection` to `Axis.horizontal`.
