### ISSUE TITLE
Full with carousel  giving white space while changing slide, how to fix?

### ISSUE THREAD

**Issue by WordpressArtist** [serenader2014/flutter_carousel_slider#23]
Full with carousel  giving white space while changing slide, how to fix? on slide the current image scale goes less and gives white space unless new slider replace it ?

**Comment by joelbrostrom** [comment]
Have you set viewportFraction to 1.0?
It defaults to 0.8 if you don't pass a value to the constructor, resulting in a 10% gap on each side.

**Comment by joelbrostrom** [comment]
@WordpressArtist Did you solve the issue?
Can the ticket be closed?
