### ISSUE TITLE
how to make the image take full width?

### ISSUE THREAD

**Issue by OrKahila** [serenader2014/flutter_carousel_slider#245]
Hey, I'm trying to make the image take full width of the screen, is there anyway to do this? ( I don't want to see the second image in the background ).

**Comment by imakevirtual** [comment]
How did you resolve it?

**Comment by MO-Lewis** [comment]
> How did you resolve it?

Late reply, but it was answered here: https://github.com/serenader2014/flutter_carousel_slider/issues/254#issuecomment-800688652
