### ISSUE TITLE
Project build with CarouselSlider.builder broken by third parameter of itemBuilder after 2.3.3 update

### ISSUE THREAD

**Issue by AlexanderMityaev** [serenader2014/flutter_carousel_slider#246]
Project doesn't build successfully after v2.3.3 update.

Code:
Widget build(BuildContext context) {
    return Scaffold(body:

    CarouselSlider.builder(
      options: CarouselOptions(height: 400.0),
      itemCount: 5,
      itemBuilder: (context, index) =>
          Container(
              width: MediaQuery.of(context).size.width,
              margin: EdgeInsets.symmetric(horizontal: 5.0),
              decoration: BoxDecoration(
                  color: Colors.amber
              ),
              child: Text('text $index', style: TextStyle(fontSize: 16.0),)
          )
    ));
 }

Now reports error on " itemBuilder: (context, index) =>".

Solved by adding third parameter, as " itemBuilder: (context, index, i) =>".

What does those realIndex mean? )

/Alexander

**Comment by vishnu-r-nair** [comment]
I had the exact same issue today after upgrading to Flutter 1.22.6 (stable), but I am still using Carousel Slider 2.3.1. Adding the third param made the errors go away. I wonder why.

**Comment by serenader2014** [comment]
Sorry for the inconvenient, this change is merged from #222 . Since it is a breaking change, I'll remove it from the v2.x version, and will publish in v3.x version.

**Comment by serenader2014** [comment]
Version v2.3.4 is published, please try to rebuild the project. Sorry for the inconvenient:(

**Comment by M123-dev** [comment]
@serenader2014, it would be great if we would add the third int and what I does to the readme
