### ISSUE TITLE
How to set Image to fit full width ?

### ISSUE THREAD

**Issue by imakevirtual** [serenader2014/flutter_carousel_slider#254]
![Screenshot_20210303-100739](https://user-images.githubusercontent.com/44916328/109754050-5d7daf80-7c09-11eb-9836-987c36a78736.png)

I don't want to see the edges of the next and previous pictures. Any solutions?

**Comment by roshanjoyp** [comment]
Set  viewportFraction to 1. It defaults to 0.8 i.e  80%. Also make sure the aspect ration of both image and widget matches.

**Comment by claranceliberi** [comment]
> Set viewportFraction to 1. It defaults to 0.8 i.e 80%. Also make sure the aspect ration of both image and widget matches.

@roshanjoyp what if I want to hide only one left part and make the middle part start at the start?

as mentioned here https://github.com/serenader2014/flutter_carousel_slider/issues/243 , https://github.com/serenader2014/flutter_carousel_slider/issues/255 and https://github.com/serenader2014/flutter_carousel_slider/issues/236

**Comment by roshanjoyrj** [comment]
@claranceliberi can you explain your query with a picture.

**Comment by claranceliberi** [comment]
@roshanjoyp  what I meant was something like this 
![image](https://user-images.githubusercontent.com/60586899/159448619-7d8a803d-56fa-484f-903c-513ed17ff702.png)
while the current version supports this and I want to get rid of this space 
![image](https://user-images.githubusercontent.com/60586899/159449924-e6f73c79-b61f-4c3a-a949-88ad35034537.png)
