### ISSUE TITLE
How to disable gesture? Can i use only .nextPage(). 

### ISSUE THREAD

**Issue by goodbaes** [serenader2014/flutter_carousel_slider#257]
How to disable gesture slider navigation/sliding/swiping? Can i use only .nextPage() for navigate in courusel?

**Comment by JasonYin8** [comment]
scrollPhysics: NeverScrollableScrollPhysics() works for me

**Comment by goodbaes** [comment]
Thank you

> scrollPhysics: NeverScrollableScrollPhysics() works for me
