### ISSUE TITLE
Non-Stop carousel

### ISSUE THREAD

**Issue by mejdi14** [serenader2014/flutter_carousel_slider#272]
hello, i'm trying to make an autoplay non-stop images slider, the first thing i tried was playing with the autoPlayInterval and autoPlayAnimationDuration but whatever i do i still have i slight pause at every image in the list.
is this possible to achieve using this library?

**Comment by prateekmedia** [comment]
There would always be some pause, do you want html marque effect, then maybe you can use horizontal list view or single child scroll view instead and do some thing to automatically make it slide continuously.

**Comment by mejdi14** [comment]
thanks bud, i will try to find another way to do it
