### ISSUE TITLE
null safty version release.

### ISSUE THREAD

**Issue by azeek** [serenader2014/flutter_carousel_slider#279]
Are there any plans to release the null safty version to the stable version?

**Comment by ghaith9cha** [comment]
Hi @azeek  
carousel null safety version is in prerelease version
[https://pub.dev/packages/carousel_slider/versions/4.0.0-nullsafety.0](url)

**Comment by UnderscoreShift** [comment]
Do we have an ETA for the stable release of null safety version?

**Comment by ghaith9cha** [comment]
Unfortunately not,
But since it is pre release version I think it is safe to use it in the app because it proceeded the alpha version beta version .
And I tried the pre release version it looks fine

**Comment by UnderscoreShift** [comment]
I saw that it's in pre-release for quite some time, but [this PR](https://github.com/serenader2014/flutter_carousel_slider/pull/271) states that there are some issues with the dev version.
Thanks!

**Comment by oscarshaitan** [comment]
I use the prerelease version and so far so good!
