### ISSUE TITLE
Feature Request : multiple items shown option 

### ISSUE THREAD

**Issue by egyleader** [serenader2014/flutter_carousel_slider#287]
I want to display more than one item on the same screen with only one be the selected one [see image below ] , and  I cannot see any option for that in _`CarouselOptions()`_ 

![ScreenShot_20210614130845](https://user-images.githubusercontent.com/31688162/121883279-d5339e00-cd11-11eb-91e8-7698ca2b5df0.png)

**Comment by jonasfranz** [comment]
Duplicate of #226
