### ISSUE TITLE
Please include Instagram type dot indicator with ability to fix maximum numbers of showing dots?

### ISSUE THREAD

**Issue by hayatbangash55** [serenader2014/flutter_carousel_slider#296]
[scrolling_page_indicator](https://pub.dev/packages/scrolling_page_indicator)  This library have this type of indicator but it is not updated from long time

Please include this feature in this library.

Like in the picture below..
![demo](https://user-images.githubusercontent.com/78781155/127489278-025fa473-d0b4-4e5d-8d54-872aabf610ce.gif)

**Comment by ndelanou** [comment]
Already been discussed in #145

I think there should be a default implementation of an indicator that you can disable from a simple parameter. This flutter package is referenced first when you search for a carousel. This would be very appreciated.

The owner of this package has chosen to let you make your own implementation, which is not a bad thing either.
What makes things a bit harder with this package is that it doesn't expose a pageController to update your indicator. You will have to implement it on the `onPageChanged` function, which is only called when the page is fully swiped.

**Comment by ayusch-apps-curefit** [comment]
Tried this but it's not working. The carousel expects a CarouselController whereas library wants PageController. Both are not interchangeable.

Could not get it working even after copying the library's code. Only if there was an option to accept PageController!
Did anyone got it working and can help ?

**Comment by hallowcard13** [comment]
Hi,  for the current version i have used additional package named dots_indicator and utilizing Carousel onPageChanged function to update dots_indicator position. Hope this helps
