### ISSUE TITLE
Auto height for different aspect ratio images?

### ISSUE THREAD

**Issue by andreaselia** [serenader2014/flutter_carousel_slider#301]
I can't tell from the docs/any of the examples. Is auto height for different aspect ratio images possible?

As in, some thin and tall images (3:4), some wide but short images (4:3).

**Comment by elkhalifte** [comment]
am looking for a fix for this too, if the carousel has an auto height will be good.

**Comment by MatheusLimaN** [comment]
+1

**Comment by andreaselia** [comment]
Duplicate of #106
