### ISSUE TITLE
Why is a height or aspect ratio required?

### ISSUE THREAD

**Issue by derekpitts28** [serenader2014/flutter_carousel_slider#303]
Why can't the carousel use the passed child widget size instead of passing a static value?

 For example if the text in a child changes size either by the user changing their OS text size or because of a translation, you now are stuck with a static height or aspect ratio that could have overflow. Can you add a Carousel option for allowing the carousel to be sized based on the child widget contents?

**Comment by philipguedes** [comment]
for anyone coming here looking for an answer for this question check #106
