### ISSUE TITLE
Flutter web swipe issue

### ISSUE THREAD

**Issue by bibash28** [serenader2014/flutter_carousel_slider#305]
The sliders are not sliding manually with the mouse.

https://user-images.githubusercontent.com/18188709/133477066-54815350-52cd-49cb-bf03-7f39bbcb2837.mp4

**Comment by RabiKumar14** [comment]
having the same issue too. It works on phone, but not responding on web

**Comment by Gusttavogs** [comment]
Having the same issue too, when i update to flutter 2.5

**Comment by Gusttavogs** [comment]
This issue is a breaking change from flutter 2.5.
Check [this](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag) documentation.
I add this line on the package, it works for me
`scrollBehavior: ScrollConfiguration.of(context).copyWith(
          dragDevices: {PointerDeviceKind.touch, PointerDeviceKind.mouse}),
![Captura de tela de 2021-09-17 08-55-50](https://user-images.githubusercontent.com/38543872/133780026-7fe6011f-8313-4a84-98b5-54e2dec25087.png)
`

**Comment by bibash28** [comment]
Thank you

**Comment by bibash28** [comment]
MaterialApp(
      builder: (_, child) => ScrollConfiguration(
        behavior: ScrollConfiguration.of(context).copyWith( 
          dragDevices: {PointerDeviceKind.touch, PointerDeviceKind.mouse},
        ),
        child: child!
      ),
    )

**Comment by cgs** [comment]
Also having this issue after the Flutter 2.5.0 update. So I'm assuming the scrollBehavior attr needs to be added to the build method in flutter_carousel_slider/lib/carousel_slider.dart? Why is this closed?

**Comment by bibash28** [comment]
Shall i re-open?

**Comment by RabiKumar14** [comment]
> ```
> return getGestureWrapper(PageView.builder(
>   scrollBehavior: ScrollConfiguration.of(context).copyWith(
>     dragDevices: {PointerDeviceKind.touch, PointerDeviceKind.mouse},
>   ),
>   physics: widget.options.scrollPhysics,
>   scrollDirection: widget.options.scrollDirection,
> ```

that solved the issue, till they update it in the build method. We can just add it on our own in the package file

**Comment by danprethink** [comment]
@RabiKumar14  When you say 'add it on our own in the package file', what do you mean? Where should we add it?

**Comment by Silfalion** [comment]
A temporary workaround:
https://stackoverflow.com/a/69202112/8568263
