### ISSUE TITLE
Latest version (1.2.0) is not on pub

### ISSUE THREAD

**Issue by benwicks** [serenader2014/flutter_carousel_slider#31]
I would like to use the enableInfiniteScroll property but 1.2.0 is not available on pub yet.

**Comment by joelbrostrom** [comment]
I don't have permission to upload to dart pub, but I'm trying to get a hold of @serenader2014 .
He has his status set to bussy though so It's hard to reach him.

**Comment by benwicks** [comment]
Ok thanks! Is there an easy way to circumvent pub and include the library directly in my project?

**Comment by serenader2014** [comment]
Sorry for the late respond. I have just published the v1.2.0 to the pub.

**Comment by benwicks** [comment]
Thank you, great library!
