### ISSUE TITLE
[Question] Is it possible to align the first image at the start of the screen?

### ISSUE THREAD

**Issue by SeanOThomas** [serenader2014/flutter_carousel_slider#319]
The first image starts in the middle of the screen with scrolling content on both sides. Is it possible to align the first image to the start of the screen?

**Comment by calebdeji** [comment]
Hi @SeanOThomas , were you able to fix this?

**Comment by SeanOThomas** [comment]
Hey @calebdeji, I ended up just using a horizontal ListView. This worked fine for my purposes.
