### ISSUE TITLE
Disable swipe

### ISSUE THREAD

**Issue by the-javatar** [serenader2014/flutter_carousel_slider#33]
Please add functionality to disable swipe for manually calling of switching pages.

**Comment by joelbrostrom** [comment]
Hi,

I suggest wrapping the carousel in an `IgnorePointer` Widget.
Anything inside the IgnorePointer will ignore touch events.
Here is an example from the first Carousel in the example project.

```
    //Manually operated Carousel
    final manualCarouselDemo = IgnorePointer(
      child:CarouselSlider(
        items: child,
        autoPlay: false,
        enlargeCenterPage: true,
        viewportFraction: 0.9,
        aspectRatio: 2.0,
      ),
    );
```

**Comment by the-javatar** [comment]
Hey I tried that it absorbs touches of the children too. Such as if I have a textfield.

**Comment by serenader2014** [comment]
I think there is no easy way to implement this feature, unless we implement our slide function, instead of using an pageview widget. But that will cost a lot of development.

**Comment by the-javatar** [comment]
Hey achieved this by adding physics: NeverScrollableScrollPhysics() to the pageview and it disabled the swipe.

**Comment by joelbrostrom** [comment]
Cool!
Do you mind adding a snippet of your code for others with the same issue?

**Comment by the-javatar** [comment]
Added a pull request
[https://github.com/serenader2014/flutter_carousel_slider/pull/43](url)
