### ISSUE TITLE
Add padEnds option in PageView.builder to remove paddings

### ISSUE THREAD

**Issue by BananaMasterz** [serenader2014/flutter_carousel_slider#337]
Could there be an option in CarouselSlider widget to allow for padEnds to be set to true/false (false as default ofc) in PageView.builder? This way if one wants to remove the starting and ending padding to the carousel while setting viewport smaller than 1, they can. Thanks.

![image](https://user-images.githubusercontent.com/45745548/157659937-58eb7056-2479-4248-a44c-20d83a287763.png)

**Comment by zae1403** [comment]
#330 fixes
