### ISSUE TITLE
NEED HELP!!!  Null check error, when i used Controller Next Page / Manualy Slide Page

### ISSUE THREAD

**Issue by madmouse17** [serenader2014/flutter_carousel_slider#339]
![Screenshot from 2022-04-03 13-01-15](https://user-images.githubusercontent.com/33163281/161414149-e0183b7e-e6f1-44eb-93ed-e4beff8fb6ae.png)
![Screenshot from 2022-04-03 13-01-37](https://user-images.githubusercontent.com/33163281/161414151-3f0f86c4-c2bd-4c88-99fc-bc54c2833ed6.png)
![Screenshot from 2022-04-03 13-01-48](https://user-images.githubusercontent.com/33163281/161414152-2f23907a-9a60-45e0-8f3b-91a0a36ba126.png)

**Comment by cedvdb** [comment]
how did you resolve that ?

**Comment by Micae1o** [comment]
How did you fix it?

**Comment by cedvdb** [comment]
you have to pass the controller to the widget

**Comment by Micae1o** [comment]
![image](https://user-images.githubusercontent.com/58992105/166504007-446b5d46-5110-4270-873e-4594b9d89192.png)

I did it. But still getting this error

**Comment by Micae1o** [comment]
I found the solution. Carousel Slider with GetX only requires CarouselCotroller to be used inside a StatefulWidget, not inside GetXController
