### ISSUE TITLE
Disable Swipe Gesuture?

### ISSUE THREAD

**Issue by seikosantana** [serenader2014/flutter_carousel_slider#359]
Hi, I am seeing if I can use this widget as step-by-step user guide. Is it possible to disable the swipe change page so user cannot change the current active page?

Thanks in advance

**Comment by RUSSCITY** [comment]
Search for the same functionality. @seikosantana did you found any solution?

**Comment by seikosantana** [comment]
I ended up using a different library

**Comment by Himanshuarora97** [comment]
You can use AbsorbPointer to disable touch on CarouselSlider
[https://stackoverflow.com/questions/54220859/flutter-disable-touch-on-the-entire-screen](stackoverflow)

**Comment by brightchip** [comment]
pass this       options: CarouselOptions(
          scrollPhysics: this.allowSwipeToChangePages
              ? null
              : NeverScrollableScrollPhysics(),

**Comment by sleewok** [comment]
> pass this options: CarouselOptions( scrollPhysics: this.allowSwipeToChangePages ? null : NeverScrollableScrollPhysics(),

Doesn't work for me...

**Comment by hadi7khan** [comment]
@seikosantana which library you used?

**Comment by seikosantana** [comment]
> @seikosantana which library you used?

@hadi7khan i no longer remember since i have moved on from flutter. I'll take a look on my source when i have access to it

**Comment by hadi7khan** [comment]
Please do, This issue is giving me headache
