### ISSUE TITLE
Trigger next / previous from within items

### ISSUE THREAD

**Issue by Kyle-Mendes** [serenader2014/flutter_carousel_slider#38]
Hey there.

I'd love to make it so an Item could have a button that the user taps to advance to the next page in the Carousel.  However, I'm struggling to figure out how to make the `PageController` available to the children, since `CarouselSlider` doesn't accept a customer `PageController`

Do you know if this is possible with the current state of the library?

Thanks!

**Comment by joelbrostrom** [comment]
Yes, I actually had this problem myself and made a temporary workaround for it.
Now that I know I'm not alone i can fix it for the repo.

Just to confirm, you want:
1. To be able to pass your pre-built `PageController `.

Is there any other criteria you have for it?

**Comment by serenader2014** [comment]
The instance returns by the `CarouselSlider` constructor in fact has some methods, such as `nextPage`, `previousPage`, and `jumpToPage`, so you can call these methods when user taps some buttons, what you need to do is to keep the instance visitable in the button's callback.

**Comment by joelbrostrom** [comment]
The problem arise when you have scrollable child (say a `ListView`) and you want to pass the `pageController` to be used as a callback, perhaps for when the `ListView` listener triggers.

This causes a paradox in which the the `ListView` need the `CarouselSlider`to be created, but the    `CarouselSlider` must be initiated with the `ListView` as a child.

For example, I want the `ListView`slowly scrolling in the background, and when a new item appears i want to check that `carousel.pageController.hasClients == true` and if so go to some page `carousel.pageController.jumpTo(somePage)`.

This would be easier by just creating a `PageController` and pass it to the `ListView` and the `CarouselSlider`.

Not the best example, but hopefully it gets the point across :)

**Comment by serenader2014** [comment]
I see. But if we pass the `PageController` to the `CarouselSlider` from the outside, then the user must maintain the `PageController` himself, that means he must set  the right `viewportFraction` and `initialPage` params for the `PageController`, that could be confusing.

**Comment by joelbrostrom** [comment]
Yes, I agree.
We could still use the generated `PageController` if no custom is passed, but it might confuse people to think it must be provided.

**Comment by Kyle-Mendes** [comment]
> Just to confirm, you want:
>
> To be able to pass your pre-built PageController .

I'm kind of new to Flutter, so IDK if this will 100% fix my use case, but I think that's correct. 

Basically, I'd like to be able to programmatically call `nextPage` from a child of the `CarouselSlider`, and I think providing my own `PageContoller` would allow me to do so. If that's not the case, then I'd probably have to think of something else :)

Thanks!

**Comment by 19smitgr** [comment]
Did this solve your problem? I'm not seeing how it's possible to pass in a PageController to the CarouselSlider since the PageController is initialized in the initializer list and is final, so I can't set the page controller of a carousel after creating it.

**Comment by joelbrostrom** [comment]
No, it's still up for grabs if you want to give it a shot!

However, I posted a workaround in issue #51 which could be applied to this.
Call nextPage or previousPage instead of printing the index.

**Comment by serenader2014** [comment]
Hi all, this issue is fixed in the `v2.0.0` release, now you can create your own `CarouselController` and pass it to `CarouselSlider`, so you can use `CarouselController` to manipulate the pageview's position. Please give it a try.
