### ISSUE TITLE
How to change  the "autoPlayInterval"  dynamically ?

### ISSUE THREAD

**Issue by devchenli** [serenader2014/flutter_carousel_slider#385]
Hello !
I want change the "autoPlayInterval" value when carousel is playing,but I can't find a way to update it.
It will not be updated  when use "setState(()=>{ _autoPlayInterval = n })"
So how can I update it ?
Thank you!

**Comment by Merculiar** [comment]
Same question, help please. setState does not work.

**Comment by Merculiar** [comment]
The only way to achieve this is to set autoloop to false and manually do all the autoplay staff by resetting/starting your own timer.
You can do it like this: 
<img width="564" alt="Screenshot 2023-02-28 at 12 26 32" src="https://user-images.githubusercontent.com/46864104/221827062-448ad899-64d9-49e5-8d99-59db02eeacbf.png">
Also do not forget to reset it in the onPageChanged function.

**Comment by MatheusFelix1796** [comment]
I got the exact same problem and found a solution:

On your state management you should have a variable, let's say "myValue" which will determine your carousel autoPlayInterval, and you would update its value (and then the widget will rebuild itself) whenever the page changed.

```
options: CarouselOptions(
  //other options here
  carouselController: carouselController,
  autoPlayInterval: Duration(seconds: myValue),
  onPageChanged: (index, reason) {
    //set your new value here, for example: item[index].time
    if (reason == CarouselPageChangedReason.controller) {
      //if you are changing pages via controller.nextPage() or controller.previousPage() then it works without problem. I was having problem with manual scrolling or after it changed automatically when the current item's autoPlayInterval time has elapsed, which are the CarouselPageChangedReason.timed and .manual reasons of page changed.
    }
    else {
      //we call animateToPage(index) to the new index (it's an animate to the same position, the same index which now is the current one after the page changed and it works!)
      carouselController!.animateToPage(index);
    }
  },
),
```

Hope it helps :)
