### ISSUE TITLE
There's no constant named 'trackpad' in 'PointerDeviceKind'

### ISSUE THREAD

**Issue by kobe-victoremanuel** [serenader2014/flutter_carousel_slider#388]
Version 4.2.0 cannot be built because of `Error: Member not found: 'trackpad'.` caused by this line:
https://github.com/serenader2014/flutter_carousel_slider/blob/f11df7496bfb314358ac8654a02882ffc6519618/lib/carousel_slider.dart#L311

**Comment by Shahadat3031** [comment]
Override the previous version 4.1.1 in the pubspec.yaml.

Example:

dependency_overrides:
carousel_slider: 4.1.1

It worked for me.

**Comment by serenader2014** [comment]
Fixed in v4.2.1, please try again.
