### ISSUE TITLE
Advice or maybe feature request:  onTap

### ISSUE THREAD

**Issue by davbaron** [serenader2014/flutter_carousel_slider#39]
I've just started using this tool and it is great. My use case is that I have a 'page' that displays a 'product' containing various text bits, plus zero or more photos (shown in the slider). The user may want to view the photos 'full screen', where they can pan and zoom, etc...  That means I need to be able to respond to a 'tap' (or double-tap) on the slider. Ideally there would be an onTap (or onDoubleTap) property for the slider widget, whereby I could have a method that would get called (along with the tapped 'index') so that I could do what i needed (open another page, etc...). In lieu of that, what would you recommend for now?  would each of my 'items' have a gesture handler, or, what?
Thanks and keep up the great work!

**Comment by haroldolivieri** [comment]
Each one of your items should be able to handle the click by its own. It will be even easier for you since each item already has the correct model you want to present.

**Comment by davbaron** [comment]
Yes, at this time I have wrapped my inner Images with GestureDetectors (looking for onTap event) and it works fine. i mainly wanted to know from the authors if this was the recommended approach, or if this or some other approach would have interfered with their own event handling (swiping). I also wanted to know their thoughts on providing this (onTap event with current index) as a built-in feature. Thanks.

**Comment by serenader2014** [comment]
It's better to handle the touch event in your child widget, I think it doesn't make sense to let the carousel slider widget to handle this feature.
