### ISSUE TITLE
PageStorage Error When Use With Hero Widget

### ISSUE THREAD

**Issue by baranngungor** [serenader2014/flutter_carousel_slider#393]
I'm getting error after upgrade Flutter 3.7.0. I'm using CarouselSlider With Hero Widget, it wasn't get error but now i see this error until Hero animation finish. My Code and error that i see: 

> Hero(
>                           tag: "${widget.heroTag}",
>                           child: CarouselSlider(
>                             options: CarouselOptions(
>                               height: context.height * 0.45,
>                               aspectRatio: 1,
>                               enlargeCenterPage: true,
>                               viewportFraction: 0.9,
>                               onPageChanged: (index, reason) {
>                                 setState(() {
>                                   currentPhotoIndex = index;
>                                 });
>                               },
>                             ),
>                             items: widget.productOption?.images!
>                                 .map((item) => Center(
>                                     child: CachedImage(url: item?.url?.big)))
>                                 .toList(),
>                           ),
>                         ),

> ════════ Exception caught by widgets library ═══════════════════════════════════
> PageStorage.of() was called with a context that does not contain a PageStorage widget.
> The relevant error-causing widget was
> CarouselSlider

![IMG_D2BA3DC47DF2-1](https://user-images.githubusercontent.com/104129460/215026524-f30a8526-c4ed-45df-9006-f36ba77f687a.jpeg)

**Comment by Tameflame** [comment]
How did you solve this? I got this exact issue today after upgrading flutter

**Comment by baranngungor** [comment]
I couldn't solve but other persons from another platform said "this is not an issue with the carousel but with how heros and inheritedwidgets work together" and "you move your call to of(context) to outside of the hero, then the value should persist during the hero flight.". I couldn't undestand but i think it doesnt about this plugin and i closed. But i'll reopen because i couldn't solve my problem and i'm not alone on this issue.

**Comment by Tameflame** [comment]
@baranngungor 
I managed to fix it: ctrl+click on that carousel_slider.dart import statement to go into the package's source code, and then modify line 358 from PageStorage.of(storageContext) to PageStorage.maybeOf(storageContext)

Simple change and it works for me.

**Comment by baranngungor** [comment]
It didn't work for me.

**Comment by MWright55** [comment]
Has any progress been made on this issue? Any new things to try?

**Comment by MWright55** [comment]
> @Tameflame It didn't work for me.

Any available work around or way to resolve the issue?

**Comment by vanomak** [comment]
Just wrap the child of the **Hero** with **PageStorage**

**Comment by baranngungor** [comment]
@vanomak it worked for me thanks.

**Comment by MohammedSalehelShazly** [comment]
It was resolved when I wrapped the Image widget with the Hero Widget directly. When an error occurred, I wrapped the CarouselSlider Widget with the Hero Widget.

**Comment by SeakyLuo** [comment]
I am having the same issue without using the `Hero`. It happens because I am enabling the `enlargeCenterPage`.
