### ISSUE TITLE
Support carousel m3

### ISSUE THREAD

**Issue by mbfakourii** [serenader2014/flutter_carousel_slider#411]
hi, if possible, support [Material 3 Carousel](https://m3.material.io/components/carousel/overview)

**Comment by kishan-dhankecha** [comment]
Hi @mbfakourii, As I can see on your provided link this feature is `planned` to be built in flutter.

https://m3.material.io/components/carousel/overview#fe9dc84e-16cd-4f80-866d-6940d00091e4
