### ISSUE TITLE
This package is not working on the new Flutter version (3.24.0).

### ISSUE THREAD

**Issue by thezuraiz** [serenader2014/flutter_carousel_slider#457]
This package is not working on the new Flutter version. Please check it out.
![WhatsApp Image 2024-08-07 at 19 44 18](https://github.com/user-attachments/assets/df087997-8226-4f28-b178-7bea70815436)

**Comment by alexboulay** [comment]
Came here to say the same!

**Comment by fawadABhatti** [comment]
I have got the same issue

**Comment by pokid** [comment]
i got the same problem

**Comment by felipecastrosales** [comment]
duplicate #454 , close this

**Comment by ixugo** [comment]
I have got the same issue

**Comment by fawadABhatti** [comment]
I have downgraded the Flutter SDK to 3.22.2 and it works.

**Comment by thezuraiz** [comment]
You can use it by placing where you have syntax errors.

`import 'package:flutter/material.dart' hide CarouselController;`

**Comment by avinash-gotluru** [comment]
@thezuraiz I have tried it but still, it's not working for me. I believe the PR has to be raised.

**Comment by thezuraiz** [comment]
Then in that case you can switch to **carousel_slider_plus** package. Someone on social media posted it's an updated version with a different name on _**Pub Dev**_ .

**Comment by avinash-gotluru** [comment]
@thezuraiz Yes, You are right we can change it to Carousel_slider_plus, Thanks for the suggestion.

**Comment by serenader2014** [comment]
fixed in v5.0.0
