### ISSUE TITLE
Acabei de atualizar para o Flutter 3.24.0 e recebi este erro:

### ISSUE THREAD

**Issue by DanielsLessa** [serenader2014/flutter_carousel_slider#458]
Could not build the precompiled application for the device.
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/carousel_slider-4.2.1/lib/carousel_slider.dart:9:1: Error: 'CarouselController' is imported from both
'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.

**Comment by porus1124962** [comment]
flutter_carousel_slider_plus: ^0.0.1 use this package. write CarouselControllerSlider instead of CarouselController

**Comment by serenader2014** [comment]
fixed in v5.0.0
