### ISSUE TITLE
Conflict between CarouselController from carousel_slider and Flutter's CarouselView

### ISSUE THREAD

**Issue by Kaif-Shariff** [serenader2014/flutter_carousel_slider#464]
### Issue
After updating to the latest Flutter version, I encountered a conflict due to the introduction of a new widget called CarouselView in the Flutter framework. This widget uses a CarouselController, which has the same name as the controller in the carousel_slider package. This naming conflict leads to the following error:

```
../../AppData/Local/Pub/Cache/hosted/pub.dev/carousel_slider-4.2.1/lib/carousel_slider.dart:9:1: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
import 'carousel_controller.dart';
```

### Solution
To resolve this issue, renaming the CarouselController class in the carousel_slider package would prevent the naming conflict with Flutter's new CarouselView widget. This change would ensure compatibility with the latest Flutter updates.

Thank you for your attention to this matter.

**Comment by narimetisaigopi** [comment]
+1

**Comment by Subrataporwal** [comment]
> +1

I deleted Pubspec.lock then install the packages and update the package to 5.0.0

**Comment by serenader2014** [comment]
Please upgrade the package to v5.0.0 version, this issue is fixed in the latest version.
