### ISSUE TITLE
is it possible to make the active carousel is at start instead center ?

### ISSUE THREAD

**Issue by buncismamen** [serenader2014/flutter_carousel_slider#47]
for now the active slider always in the center 
![Screenshot_20190514-161741](https://user-images.githubusercontent.com/14258779/57686981-cc6ccb80-7664-11e9-9a98-8d2563c5677e.png)

how to make it so the active slider is at the start instead center like this ?
![Screenshot_20190514-161734](https://user-images.githubusercontent.com/14258779/57687028-e1e1f580-7664-11e9-92cd-7dda4f65b721.png)

edit: it seems not possible consider to use horizontal listview instead

**Comment by xok-comet** [comment]
how you fix it?

**Comment by buncismamen** [comment]
see my last edit 

it seems not possible consider to use horizontal listview instead
