### ISSUE TITLE
Please fully support FLUTTER 3.24 and make sure theirs is no warnings or deprecations please 

### ISSUE THREAD

**Issue by fisforfaheem** [serenader2014/flutter_carousel_slider#471]
i am getting projectuild failed ===== CRASH =====
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF7B394B9BC
the Dart compiler exited unexpectedly.

Exited (1).

**Comment by sawongam** [comment]
same error here

**Comment by serenader2014** [comment]
Please upgrade to v5.0.0 version. This issue is fixed in v5.0.0
