### ISSUE TITLE
User click on item instead of scrolling

### ISSUE THREAD

**Issue by joaquinperaza** [serenader2014/flutter_carousel_slider#51]
During testing we analyzed UX and detected people prefer to click on image rather than scrolling to select a new item, I know this widget is not intended for that, however, it would be useful to add that feature.

![Image of app](https://snag.gy/L0JCpu.jpg)

**Comment by joelbrostrom** [comment]
Hi!

You want to be able to scroll through the items, but also be able to click any item on screen.
Have I understood you correctly?

If so this can be easily done by wrapping your elements in a `GestureDetector` and set `onTap` to your select item function.

Using the example project from our GitHub repo all I had to do was wrapping each item in a GestureDetector and added `print(index)` on its `onTap` argument.

With only 3 lines of code all the items in the demo is clickable!

```
final List child = map<Widget>(
  imgList,
  (index, i) {
    return GestureDetector(
      onTap: ()=> print(index) ,
      child: Container(
        margin: EdgeInsets.all(5.0),
        child: ClipRRect(
          borderRadius: BorderRadius.all(Radius.circular(5.0)),
          child: Stack(children: <Widget>[
            Image.network(i, fit: BoxFit.cover, width: 1000.0),
            Positioned(
              bottom: 0.0,
              left: 0.0,
              right: 0.0,
              child: Container(
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    colors: [Color.fromARGB(200, 0, 0, 0), Color.fromARGB(0, 0, 0, 0)],
                    begin: Alignment.bottomCenter,
                    end: Alignment.topCenter,
                  ),
                ),
                padding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 20.0),
                child: Text(
                  'No. $index image',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20.0,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ),
          ]),
        ),
      ),
    );
  },
).toList();
```

**Comment by joaquinperaza** [comment]
Great, I have been trying to do something like that, I got stuck when trying to cal goto(int index) from the gesture detector as I couldn't reference the carousel itself, but i think is possible

**Comment by GeoffGodwin** [comment]
@joelbrostrom I noticed that if the carousel is mid-animation, then the onTap function doesn't fire. The movement has to come to a complete stop which, from a UX perspective, causes a rather obvious "I clicked and nothing happened" feeling when attempting to click on an individual element.

Any idea why this would be?
