### ISSUE TITLE
Parallax effect

### ISSUE THREAD

**Issue by Kamel38** [serenader2014/flutter_carousel_slider#54]
Is it possible to create a parallax effect with the images displayed ? 
I tried to mix it with other parallax plugins but I needed the controller and was unable to get it from the source code.

Anyone has an idea on how to do a parallax effect with carousel_slider plugin ?

**Comment by mortadda** [comment]
you can use animation bulider to do this :


first define your controller and animation tween :
```

  AnimationController _animationController;
  Animation<Offset>  _parallaxTween;

```

second init your state widget:
```
  void initState() {
    _animationController =
        AnimationController(vsync: this, duration: Duration(seconds: 0));
    _parallaxTween = Tween(begin: Offset(0, 0), end: Offset(0, 60))
        .animate(_animationController);
    super.initState();
  }

```

```
   AnimatedBuilder(
                      animation: _animationController,
                      builder: (context, child) => Transform.translate(
                        offset: _parallaxTween.value,
                           //here  define what you want 
                        child: Carousel([1, 2, 3, 4]
                            .map((i) => "assets/images/products/$i.jpg")
                            .toList()),
                      ),
            ),
```


result:
![peekQN4Z4Z](https://user-images.githubusercontent.com/11082696/61331843-fa72b580-a837-11e9-9851-d7fb5dbc70da.gif)

**Comment by santhisagar** [comment]
@serenader2014 It would be easy if Parallax effect is provided in the package itself
