### ISSUE TITLE
Multiple Carousels: swipe scrolls all

### ISSUE THREAD

**Issue by Martibis** [serenader2014/flutter_carousel_slider#59]
I have multiple Carousels on my page, horizontal swiping one, makes them all go to the next / previous image, whilst it should only be the one being swiped on.

**Comment by joelbrostrom** [comment]
Try looking at the example project in the example folder of this repo.
There we have several carousels lined up vertically and this does not appear.

Please post what was the error so this issue can be closed and others in the same situation can find it.

**Comment by serenader2014** [comment]
Closing this issue since there is no more reply.

**Comment by Martibis** [comment]
I lost track of this, I managed to fix it if I recall correctly I solved it by adding Unique Keys (in case others stumble upon this problem).
