### ISSUE TITLE
Non-looping setting

### ISSUE THREAD

**Issue by brettpappas** [serenader2014/flutter_carousel_slider#6]
Is there a way to prevent the carousel from looping around to the start?

In other words - if I have 3 items, I want to prevent the user from sliding past the third item. They would need to swipe the other direction to get back to the first item.

I love the plugin but I want to use it for a set of cards that someone can swipe through and it would make more sense to have the user swipe back and forth if there are only 2 cards.

**Comment by mennorenkens** [comment]
@brettpappas I had the same problem. Solved it by adding a Container() at the start and the end of the list that goes into the carousel. Then just use the previousPage() and nextPage() functions to immediately go back (and thus prevent from looping). It works pretty well! 

`updateCallback: (index) {
              if (index == 0) { // bounce-back to start of slider
                cardSlider.nextPage(
                  duration: Duration(milliseconds: 200),
                  curve: Curves.linear,
                );
              } else if (index == (items.length - 1)) { // bounce-back to end of slider
                cardSlider.previousPage(
                  duration: Duration(milliseconds: 200),
                  curve: Curves.linear,
                );
              }`

**Comment by ziofat** [comment]
@mennorenkens Your workaround is great for simple situation. However I need to embed my carousel in a tab, and scroll to next tab. 

@serenader2014 If you create this package for looping feature, could you suggest the non-looping package you used.

**Comment by albo1337** [comment]
@mennorenkens What is your cardSlider? I'm facing the same problem actually.

**Comment by mennorenkens** [comment]
@albo1337 here is the full code. Now I'm only placing the 'cardSlider' as a child of a Container() somewhere else.

```dart
CarouselSlider cardSlider;
    cardSlider = new CarouselSlider(
      initialPage: 2,
      height: 110.0,
      items: shifts.toList(),
      viewportFraction: 0.85,
      aspectRatio: 2.0,
      updateCallback: (index) {
        if (index == 1) {
          // bounce-back to start of slider
          cardSlider.nextPage(
            duration: Duration(milliseconds: 200),
            curve: Curves.linear,
          );
        } else if (index == 0) {
          // bounce-back to end of slider
          cardSlider.previousPage(
            duration: Duration(milliseconds: 200),
            curve: Curves.linear,
          );
        }
      },
    );
```

**Comment by S1r-Lanzelot** [comment]
One issue I am having in relation to this is when I use a hero for each item in the my carousel's list/array... For example, if I have one item in my array, I cannot use that item's identifier for the hero tag because it is duplicated in the carousel, I wish their was a way to maybe access the realIndex num to get a truly unique identifier for the carousel item.

**Comment by abc873693** [comment]
I need this feature because use hero animation. Tag will repeat and crash. Thanks

**Comment by localpcguy** [comment]
Not being able to turn off infinite scroll makes this not an option. On the positive side, it was really simple to get the widget working.

**Comment by joelbrostrom** [comment]
Since this seams to be a recurring request I just made a PR with this feature.
@serenader2014  If you think the lib will benefit from it go ahead and merge it :)

**Comment by joelbrostrom** [comment]
This is implemented, but needs to be uploaded to Dart Pub for flutter distribution.
@serenader2014

**Comment by joelbrostrom** [comment]
Added in 1.2.0!
