### ISSUE TITLE
if you scroll down using scrollview, widget will rebuild again from index 0

### ISSUE THREAD

**Issue by muhammadsaddamnur** [serenader2014/flutter_carousel_slider#60]
if you scroll down using scrollview, widget will rebuild again from index 0

**Comment by joelbrostrom** [comment]
Do you have some example code?

**Comment by tigertore** [comment]
I have seen and fixed the same issue.
Our app has a long vertical scrollview with a lot of content,
and at the top we have a horizontal carousel slider (viewportFraction: 0.333).
To fix the issue I had to add a PageStorageKey like this:
 @override
  Widget build(BuildContext context) {
    return getWrapper(PageView.builder(
      key:PageStorageKey("CarouselSlider_slides"),
      physics: widget.scrollPhysics,

**Comment by serenader2014** [comment]
Fixed in v2.1.0, you can pass a `pageviewKey` option to keep the pageview's position.
