### ISSUE TITLE
The element type 'CarouselSlider' can't be assigned to the list type 'Widget'

### ISSUE THREAD

**Issue by zeromaro** [serenader2014/flutter_carousel_slider#64]
Hello,
When trying to execute 

```
@override
  Widget build(BuildContext context) {
    return Column(children: [
      CarouselSlider(
        items: child,
        autoPlay: true,
        enlargeCenterPage: true,
        aspectRatio: 2.0,
      )
    ]);
  }
```

I receive an error 

> The element type 'CarouselSlider' can't be assigned to the list type 'Widget'

I'm very confused on solving it. 

P.S. Im trying it out on Flutter WEB.

**Comment by zeromaro** [comment]
Okay, solved it. Plugins doesn't work on Flutter WEB as for this day. However cloning repo and working with it internally worked.

**Comment by l-k22** [comment]
How did you solve this, I'm getting the same error but I'm not using FlutterWeb
