### ISSUE TITLE
Add flutter_carousel_slider to Flutter Arsenal

### ISSUE THREAD

**Issue by flutter-arsenal** [serenader2014/flutter_carousel_slider#66]
flutter_carousel_slider can be added to FlutterArsenal to help with reach, accessibility and ease-of-use. [Flutter Arsenal](https://flutterarsenal.com) is a directory that is being curated for Flutter libraries and tool. The best way to do is by creating an issue on [github](https://github.com/flutterarsenal/FlutterArsenal/issues/new/choose).

**Comment by joelbrostrom** [comment]
Interesting!
I will look into it if I get time.
Whats the pro of this service over pub.dev?
More visually pleasing?

**Comment by IAmSarthakVerma** [comment]
Hello @joelbrostrom, pub.dev just allows you to search the Flutter "packages". Flutter Arsenal is a categorized directory of not just "packages" but also reusable UI Modules and other tools which is not always a "Flutter Package".  When we say "categorized directory" here, it is more than just categorizing it as "Flutter" or "Flutter Web".

**Comment by borsezf2** [comment]
i would like to contribute with this.
i have worked on similar things

**Comment by joelbrostrom** [comment]
Would you like to add it to Arsenal, or just developing in general?
