### ISSUE TITLE
How to remove the effect of change page in the first ou last page when infinitePage off?

### ISSUE THREAD

**Issue by LeandroMoura3** [serenader2014/flutter_carousel_slider#67]
I want remove the blue effect below.

I discovery that this color is the ThemeDate.accentColor. But if I change it, the alpha is setting to a constant that I don't control. Because of this, I can't put this effect with Colors.transparent. In this case, the effect will be black with the constant alpha.

Someone have any ideia to change this alpha constant to zero?

![image](https://user-images.githubusercontent.com/50925660/64276147-97d79500-cf1d-11e9-856b-c08485a13604.png)

**Comment by joelbrostrom** [comment]
Hi!
A carousel is built upon a `PageView`, which has a property `physics` that determines how the items should behave when they are scrolled. 
In this case flutter_carousel was first designed to be an infinite loop (i.e. carousel) with no end or beginning. 
It has however become popular to use in other situations as well, so more functionality has been added along the way.  

What you are looking for is the `physics` property of the `PageView` the carousel builds. 
It defaults to the platform specific physics, but you want to change it to `BouncingScrollPhysics()`, which will give it a little bounce if no more items exist but no shadow/color effect will show.

Just to make it clear. 
This is not supported yet and you would have to fork the repo and change it yourself.

**Comment by joelbrostrom** [comment]
Hi, again!

I added scrollPhysics to the carousel slider. 
All you have to do is update to 1.3.1 and pass `BouncingScrollPhysics()` to the new constructor argument `scrollPhysics`.

Hope it solves your problem :)

**Comment by LeandroMoura3** [comment]
It solves. Thank you!
