### ISSUE TITLE
Timer for auto-play doesn't reset when nextPage/previousPage is called

### ISSUE THREAD

**Issue by gogori2** [serenader2014/flutter_carousel_slider#72]
I wanted to keep auto-play and change pages with buttons, but seems like `.nextPage` and
 `.previousPage` doesn't trigger `auseAutoPlayOnTouch`.

**Comment by serenader2014** [comment]
Yes, it's a known issue. Will look into it if I have time. Also, PR is welcome.

**Comment by serenader2014** [comment]
Yes, it's a known issue. Will look into it if I have time. Also, PR is welcome.

**Comment by serenader2014** [comment]
Fixed in v2.1.0
