### ISSUE TITLE
Controller

### ISSUE THREAD

**Issue by BugsBunnyBR** [serenader2014/flutter_carousel_slider#76]
How about to move the methods from the carousel instance to a controller? It would be more familiar with other widgets apis.

**Comment by noinskit** [comment]
+1, this would also make changing pages from outside a CarouselSlider easier and safer.

**Comment by rockingdice** [comment]
bump this. Currently, I cannot sync the page index will an outside page indicator.

**Comment by HugoHeneault** [comment]
I started working on it. It's quite some work!

**Comment by HugoHeneault** [comment]
I just pushed #115 if you guys wanna review & test it! 🍻
