### ISSUE TITLE
Unhandled Exception: setState() called after dispose()

### ISSUE THREAD

**Issue by tonyclickspace** [serenader2014/flutter_carousel_slider#80]
From the console:

> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _CarouselSliderState#fc80e(lifecycle state: defunct, not mounted)
> This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
> The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
> This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

This happened when scrolling very quickly through 150 line items, in debug mode, in a simulator (so a bit slower processing than in production), each with a CarouselSlider object. This code would appear to be the issue? Adding an `isDisposed` bool and checking it before calling setState is probably the easiest fix.

```
// on the first render, the pageController.page is null,
// this is a dirty hack
if (widget.pageController.position.minScrollExtent == null ||
  widget.pageController.position.maxScrollExtent == null) {
  Future.delayed(Duration(microseconds: 1), () {
    setState(() {});
  });
}
```

**Comment by serenader2014** [comment]
Fixed in v1.4.0
