### ISSUE TITLE
Use Transform.scale instead of SizedBox 

### ISSUE THREAD

**Issue by markusgeert** [serenader2014/flutter_carousel_slider#86]
When I have the center page enlarged option set to true, widgets like text and padding on the not-center pages aren't resized. Because my pages contain a column with the mainAxisAlignment set to spacebetween, the spacing between items on these pages change depending on the exact scrollposition between two carouselitems. 
Transform.scale gets rid of this problem by scaling everything that is inside the parent item, instead of just setting the height, which doesn't affect the child widgets of the page in terms of size.

**Comment by markusgeert** [comment]
I have solved this problem by replacing the SizedBox by a container with the appropriate height and wrapped that in a Transform.scale. 
It seems to be working the same as the SizedBox did.
If there is any demand for this feature I can create a pull-request.

**Comment by bizz84** [comment]
@markusgeert Yes, I bumped into this same problem. It would be great to have a PR for this.

**Comment by serenader2014** [comment]
Hi @markusgeert , thank you for reporting this issue. I'll take a look at this problem. And PR is always welcome :)

**Comment by markusgeert** [comment]
> 
> 
> Hi @markusgeert , thank you for reporting this issue. I'll take a look at this problem. And PR is always welcome :)

Added a PR to solve this

**Comment by serenader2014** [comment]
Fixed in v2.1.0
