### ISSUE TITLE
Add the ability to get the exact scrollposition of the carousel inside another widget

### ISSUE THREAD

**Issue by markusgeert** [serenader2014/flutter_carousel_slider#87]
I want to format the page indicators depending on how far the carousel is scrolled towards the next page. In order to do this I need to access the variable 'value' that is defined inside the state of the carousel. 
One way this can be achieved is by adding a callback function that returns the variable 'value' and is called when this variable is changed.

**Comment by markusgeert** [comment]
I have solved this by adding the variable 'onScrolled' to the CarouselSlider class. This is a callback function that returns a double. I edited the getWrapper function to wrap its input in a notificationlistener that listens to the ScrollUpdateNotification, and executes the onScrolled function accordingly. 
If this feature is requested, I can make a pull request for it.

**Comment by serenader2014** [comment]
Can you please open a PR?

**Comment by markusgeert** [comment]
Opened a PR for this function.

**Comment by serenader2014** [comment]
Closing this issue since the PR is merged.
