### ISSUE TITLE
feature require: multiple items on one screen.

### ISSUE THREAD

**Issue by imakou** [serenader2014/flutter_carousel_slider#88]
Hi,

This widget is lovely :)

Is it possible to support multiple items on one screen?
Many thanks.

![image](https://user-images.githubusercontent.com/1507950/71687828-a5d2e080-2d6c-11ea-8ce0-9ba22e9b5b6f.png)

**Comment by serenader2014** [comment]
Sorry, this is not possible right now.

**Comment by amreniouinnovent** [comment]
@imakou you could use viewportFraction for now
