### ISSUE TITLE
Version solving failed with Dart SDK >2

### ISSUE THREAD

**Issue by vortixhead** [serenader2014/flutter_carousel_slider#9]
I am having this error message while running 'flutter packages get' after upgrading flutter:

Because XXXX depends on carousel_slider >=0.0.2 which requires SDK version >=1.8.0 <2.0.0, version solving failed.

Will there be support for SDK > 2.0.0 ? Is there a workaround?

Thanks for the awesome package

**Comment by serenader2014** [comment]
Yes, it should be compatible with SDK 2.0.0, I'll publish a new version to the pub when I have time, sorry for the inconvenient.

**Comment by serenader2014** [comment]
I have published a new version to the pub server, and it's supporting SDK 2.0. Please upgrade to the latest version.
