### ISSUE TITLE
Widget reloaded - performance issue

### ISSUE THREAD

**Issue by enricobenedos** [serenader2014/flutter_carousel_slider#93]
My app flow:
- Get base64 encoded string (that represent my image) from my API
- Convert it to an image
- Show it in the carousel slider

I use a custom widget to show/contain images because I need to manually cache them. The problem is that when I slide between the images in the carousel (also autoplay=true), the third one is always reloaded even if I have saved the image in a local list (`List<Base64Image> _tourImages = List<Base64Image>();`). This cause a very fastidious lag, I call some setstate during Base64Image widget load. But once it is loaded I expect that the image is return without any lag because it is already loaded. It seems like carousel widget dispose my widget and the reload it, in fact init state is recalled.

** `getImageUrl()` is only a method that return the url that I need to call to obtain the base 64 string, the url is used also as file name in the cache **

Here my custom image class:
```dart
class Base64Image extends StatefulWidget {
  final String imgUrl;

  const Base64Image({Key key, this.imgUrl}) : super(key: key);

  @override
  _Base64ImageState createState() => _Base64ImageState();
}

class _Base64ImageState extends State<Base64Image> {
  Image _image;

  @override
  void initState() {
    super.initState();

    //Check if image already exists
    DefaultCacheManager().getFileFromCache(widget.imgUrl).then((onValue) {
      if (onValue != null) {
        final Uint8List imageBytes = onValue.file.readAsBytesSync();
        setState(() {
          _image = Image.memory(
            imageBytes,
            fit: BoxFit.fill,
          );
        });
      } else {
        HTTPService.getImage(widget.imgUrl).then((onValue) {
          final Uint8List imageBytes = base64Decode(onValue.imageBytes);
          DefaultCacheManager().putFile(widget.imgUrl, imageBytes);

          setState(() {
            _image = Image.memory(
              imageBytes,
              fit: BoxFit.fill,
            );
          });
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return _image == null ? Center(child: CircularProgressIndicator()) : _image;
  }
}
```
My carousel implementation
```dart
class RoutePage extends StatefulWidget {
  final Tour tour;

  const RoutePage({Key key, this.tour}) : super(key: key);

  @override
  _RoutePageState createState() => _RoutePageState();
}

class _RoutePageState extends State<RoutePage> {
  // List<String> _carouselImagesUrls = List<String>();
  List<Base64Image> _tourImages = List<Base64Image>();
  String _summary;

  @override
  void initState() {
    super.initState();

    //Get all images urls
    for (String imgName in widget.tour.imgsPaths.split(';')) {
      // _carouselImagesUrls.add(HTTPService.getImageUrl(
      //     ImageType.TourImage, widget.tour.id, imgName));
      final String imgUrl =
          HTTPService.getImageUrl(ImageType.TourImage, widget.tour.id, imgName);
      _tourImages.add(Base64Image(
        imgUrl: imgUrl,
      ));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SingleChildScrollView(
          child: Column(
            children: <Widget>[
              ...
              SizedBox(
                height: 300,
                child:
                    CarouselSlider.builder(
                        autoPlay: true,
                        enlargeCenterPage: true,
                        aspectRatio: 2.0,
                        itemCount: _tourImages.length,
                        itemBuilder: (BuildContext context, int itemIndex) =>
                            Container(
                              child: ClipRRect(
                                borderRadius:
                                    BorderRadius.all(Radius.circular(5.0)),
                                child: _tourImages[itemIndex],
                              ),
                            )),
                //     CarouselSlider(
                //   autoPlay: true,
                //   enlargeCenterPage: true,
                //   aspectRatio: 2.0,
                //   items: _tourImages,
                // ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12233746/72194282-4ed4a780-340d-11ea-80c5-c36e18df7dc0.gif)

**Comment by sanekyy** [comment]
This is how the Lists works in Flutter

**Comment by enricobenedos** [comment]
Hey @sanekyy are you speaking about List type or ListView widget? In my case I'm not using ListView widget but the problems exists anyway. In the repository example the problem does not exist and they are using ListViews. I'm trying to find a solution as in your case

**Comment by sanekyy** [comment]
@enricobenedos 
I tried to describe my problem [here](https://github.com/flutter/flutter/issues/49126)

**Comment by dnfield** [comment]
You're probably not getting a cache hit - is your new image implementation using a sensible key?

**Comment by sanekyy** [comment]
Image loading is not my problem:)

**Comment by enricobenedos** [comment]
@dnfield the problem is that my Base64Image widget, that is a custom image cache widget, is disposed and recreated every time it is loaded on the “third position(right)” of the carousel. I’m trying to understand if it is a problem related to this plugin or flutter implementation. My widget is disposed also implementing AutomaticKeepAliveClientMixin.

**Comment by sanekyy** [comment]
As I understood, your cache should work even if widget recreated. So, if it don't, it's problem of your cache.

If we talk about  disposing and recreating -> it is a how Flutter works. I described this behaviour in my issue in details. Also AutomaticKeepAliveClientMixin does't help in this situation, because you use infinite/looped carousel. It will keep alive all previous widgets. You can see it, if you will scroll front and then scroll back .

**Comment by enricobenedos** [comment]
> As I understood, your cache should work even if widget recreated. So, if it don't, it's problem of your cache.

Yes, my cache mechanism work when widget is loaded (recalled initState) and there is a small memory read and image instantiation time that is not a problem normally but in this case it is fastidious. But as you can see in my code I've created a `List<Base64Image>` in the `RoutePage` widget, so once the list is created the Base64Image widgets are loaded and as long as `RoutePage` is not disposed I will expect that my list of `Base64Image` are not disposed and reloaded. In the worst case the widget will be rebuilt but it is not a problem because the image is in the device memory. Hope I will clarified what I mean :)

> If we talk about disposing and recreating -> it is a how Flutter works. I described this behaviour in my issue in details. Also AutomaticKeepAliveClientMixin does't help in this situation, because you use infinite/looped carousel. It will keep alive all previous widgets. You can see it, if you will scroll front and then scroll back .

I read your issue and, from above of my ignorance I understood that is a Flutter limitation.

But are you telling me that if I execute this code snippets contained in the plugin sample:
```dart
final CarouselSlider autoPlayDemo = CarouselSlider(
      viewportFraction: 0.9,
      aspectRatio: 2.0,
      autoPlay: true,
      enlargeCenterPage: true,
      items: imgList.map(
        (url) {
          return Container(
            margin: EdgeInsets.all(5.0),
            child: ClipRRect(
              borderRadius: BorderRadius.all(Radius.circular(5.0)),
              child: Image.network(
                url,
                fit: BoxFit.cover,
                width: 1000.0,
              ),
            ),
          );
        },
      ).toList(),
    );
```
the Image (statefull) widget is always reloaded? I think no because the sample works perfectly. What is the difference?

**Comment by sanekyy** [comment]
Image.network under the hood use CachedImage which keeps alive even if all Image widgets will disposed.

**Comment by enricobenedos** [comment]
I've tried with a lot of solution but no one works.
@dnfield sorry for late reply but the answer is no.
Now I'm using `flutter_advanced_networkimage 0.7.0` as item/s to include on carousel but the result does not change. I think I will close this issue even if I'm very afraid about this.
