### ISSUE TITLE
Controller creates on each build

### ISSUE THREAD

**Issue by sanekyy** [serenader2014/flutter_carousel_slider#95]
Hello.
As I see in source code, controller creating on each build of carousel widget.
Can you move it into _CarouselSliderState?

![image](https://user-images.githubusercontent.com/18647037/72753770-dde47b00-3bd6-11ea-9dca-ab18c35392ed.png)

**Comment by serenader2014** [comment]
Hi, sorry for the late response.

Ahh, yes, the controller should be created in the _CarouselSliderState. Will fix this in next release.

**Comment by serenader2014** [comment]
Fixed in v2.0.0.
