### ISSUE TITLE
Update the examples to show the images being loaded. 

### ISSUE THREAD

**Issue by pradt** [serenader2014/flutter_carousel_slider#98]
Hi this is just a suggestion, I was going through the documentation and noticed that the examples (animated screenshots) didn't align with the code examples. Is it possible to update the documentation to have the animated screenshots aligned with the code example ?

**Comment by serenader2014** [comment]
Hi, sorry for the late response.

Of course, will update the doc in next release.

**Comment by serenader2014** [comment]
Screenshot updated.
