### ISSUE TITLE
Why does the CarouselSlider slide automatically?

### ISSUE THREAD

**Issue by minikupa** [serenader2014/flutter_carousel_slider#99]
bool first = true;

  @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      setState(() {
        first = false;
      });
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    initChild();
    print(first);
    return CarouselSlider(
      height: 260,
      viewportFraction: 1.0,
      autoPlay: first,
      items: child,
    );
  }

after setState
print(first) -> false
Why does the CarouselSlider slide automatically?

**Comment by serenader2014** [comment]
Because you've set the `autoPlay` option to `true`. To disable the auto play feature just pass `false` in the `autoPlay` option.
